# Generated by Django 4.0.5 on 2022-10-02 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foydalanuvchi', '0092_alter_hisobot_ich_options_alter_hisobot_ist_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='filtr_faqir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foydalanuvchi.allfaqir', verbose_name='Korxonalar')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'filtr_faqir',
                'verbose_name_plural': 'filtr_faqirs',
            },
        ),
    ]
