# Generated by Django 4.0.5 on 2022-10-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minenergiya', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filtr_faqir',
            options={'verbose_name': 'Filtr korxonasi', 'verbose_name_plural': '01_Filtr uchun Korxonalar'},
        ),
    ]
