# Generated by Django 4.0.5 on 2022-10-02 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0092_alter_hisobot_ich_options_alter_hisobot_ist_options_and_more'),
        ('minenergiya', '0002_alter_filtr_faqir_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtr_faqir',
            name='fqr',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='foydalanuvchi.allfaqir', verbose_name='Korxonalar'),
        ),
        migrations.AlterField(
            model_name='filtr_faqir',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi'),
        ),
    ]
