# Generated by Django 4.0.5 on 2022-10-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minenergiya', '0004_guruh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guruh',
            options={'verbose_name': 'guruh', 'verbose_name_plural': '02_guruhlar'},
        ),
    ]
