# Generated by Django 4.0.5 on 2022-10-04 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_ad', '0038_alter_tadbir_options'),
        ('foydalanuvchi', '0093_alter_allfaqir_thst'),
        ('minenergiya', '0005_alter_guruh_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guruh',
            name='fqr',
            field=models.ManyToManyField(blank=True, to='minenergiya.filtr_faqir', verbose_name='Foydalanuvchilar'),
        ),
        migrations.CreateModel(
            name='ensamfiltr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.TextField(unique=True, verbose_name='nomi')),
                ('tur', models.TextField(unique=True, verbose_name='Hisobot turi')),
                ('vaqt', models.DateTimeField(verbose_name='Vaqti')),
                ('dan', models.DateField(verbose_name='dan')),
                ('gacha', models.DateField(verbose_name='gacha')),
                ('fqr', models.ManyToManyField(blank=True, to='foydalanuvchi.allfaqir', verbose_name='Foydalanuvchilar')),
                ('olchov', models.ManyToManyField(blank=True, to='s_ad.birliklar', verbose_name='O`lchov birligi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
                ('resurs', models.ManyToManyField(blank=True, to='s_ad.resurslar', verbose_name='Resurs')),
            ],
            options={
                'verbose_name': 'ensamfiltr',
                'verbose_name_plural': '03_Energiya samaradorlik bazasi',
            },
        ),
    ]
