# Generated by Django 4.0.5 on 2022-10-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minenergiya', '0006_alter_guruh_fqr_ensamfiltr'),
    ]

    operations = [
        migrations.CreateModel(
            name='tur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guruh', models.BooleanField(verbose_name='Guruhiy')),
            ],
            options={
                'verbose_name': 'tur',
                'verbose_name_plural': 'turlar',
            },
        ),
    ]
