# Generated by Django 4.0.5 on 2022-10-11 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minenergiya', '0007_tur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensamfiltr',
            name='tur',
        ),
    ]
