# Generated by Django 4.0.5 on 2022-10-11 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minenergiya', '0008_remove_ensamfiltr_tur'),
    ]

    operations = [
        migrations.AddField(
            model_name='tur',
            name='ixtiyoriy',
            field=models.BooleanField(default=1, verbose_name='ixtiyoriy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tur',
            name='owner',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tur',
            name='xususiy',
            field=models.BooleanField(default=1, verbose_name='xususiy'),
            preserve_default=False,
        ),
    ]
