# Generated by Django 4.0.5 on 2022-10-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minenergiya', '0009_tur_ixtiyoriy_tur_owner_tur_xususiy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tur',
            name='guruh',
        ),
        migrations.RemoveField(
            model_name='tur',
            name='ixtiyoriy',
        ),
        migrations.RemoveField(
            model_name='tur',
            name='xususiy',
        ),
        migrations.AddField(
            model_name='tur',
            name='tur',
            field=models.TextField(default=1, unique=True, verbose_name='nomi'),
            preserve_default=False,
        ),
    ]
