# Generated by Django 4.0.5 on 2022-10-13 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minenergiya', '0010_remove_tur_guruh_remove_tur_ixtiyoriy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tur',
            name='tur',
            field=models.TextField(unique=True, verbose_name='Turi'),
        ),
        migrations.CreateModel(
            name='guruhiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guruh', models.TextField(unique=True, verbose_name='Turi')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'fitr furuhi',
                'verbose_name_plural': 'filtr guruhlari',
            },
        ),
    ]
