# Generated by Django 4.0.5 on 2022-10-13 03:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minenergiya', '0011_alter_tur_tur_guruhiy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='guruhiy',
            new_name='klassifikator',
        ),
    ]
