# Generated by Django 4.0.5 on 2022-10-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minenergiya', '0012_rename_guruhiy_klassifikator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klassifikator',
            old_name='guruh',
            new_name='klass',
        ),
    ]
