# Generated by Django 4.0.5 on 2022-10-14 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minenergiya', '0013_rename_guruh_klassifikator_klass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klassifikator',
            options={'verbose_name': 'klassifikator', 'verbose_name_plural': 'klassifikatorlar'},
        ),
    ]
