# Generated by Django 4.0.5 on 2022-10-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minenergiya', '0015_remove_ensamfiltr_resurs_ensamfiltr_e_id_guruh_e_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtr_faqir',
            name='E_ID',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='E_ID'),
        ),
        migrations.AlterField(
            model_name='ensamfiltr',
            name='E_ID',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='E_ID'),
        ),
        migrations.AlterField(
            model_name='guruh',
            name='E_ID',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='E_ID'),
        ),
        migrations.AlterField(
            model_name='klassifikator',
            name='E_ID',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='E_ID'),
        ),
        migrations.AlterField(
            model_name='tur',
            name='E_ID',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='E_ID'),
        ),
    ]
