# Generated by Django 4.0.5 on 2022-10-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minenergiya', '0016_filtr_faqir_e_id_alter_ensamfiltr_e_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensamfiltr',
            name='fqr',
        ),
        migrations.AddField(
            model_name='ensamfiltr',
            name='filtr_faqir',
            field=models.ManyToManyField(blank=True, to='minenergiya.filtr_faqir', verbose_name='Foydalanuvchilar'),
        ),
        migrations.AddField(
            model_name='ensamfiltr',
            name='guruh',
            field=models.ManyToManyField(blank=True, to='minenergiya.guruh', verbose_name='Guruhlar'),
        ),
        migrations.AddField(
            model_name='ensamfiltr',
            name='klassifikator',
            field=models.ManyToManyField(blank=True, to='minenergiya.klassifikator', verbose_name='klassifikator'),
        ),
        migrations.AddField(
            model_name='ensamfiltr',
            name='tur',
            field=models.ManyToManyField(blank=True, to='minenergiya.tur', verbose_name='tur'),
        ),
        migrations.RemoveField(
            model_name='ensamfiltr',
            name='olchov',
        ),
        migrations.AddField(
            model_name='ensamfiltr',
            name='olchov',
            field=models.TextField(blank=True, verbose_name='O`lchov birliklari'),
        ),
    ]
