# Generated by Django 4.0.5 on 2022-10-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minenergiya', '0017_remove_ensamfiltr_fqr_ensamfiltr_filtr_faqir_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ensamfiltr',
            options={'verbose_name': 'ensamfiltr', 'verbose_name_plural': '0_Universal filtr bazasi'},
        ),
        migrations.RemoveField(
            model_name='ensamfiltr',
            name='vaqt',
        ),
        migrations.AddField(
            model_name='ensamfiltr',
            name='sana',
            field=models.DateTimeField(default=1, verbose_name='sana'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ensamfiltr',
            name='filtr_faqir',
            field=models.ManyToManyField(blank=True, null=True, to='minenergiya.filtr_faqir', verbose_name='Foydalanuvchilar'),
        ),
        migrations.AlterField(
            model_name='ensamfiltr',
            name='guruh',
            field=models.ManyToManyField(blank=True, null=True, to='minenergiya.guruh', verbose_name='Guruhlar'),
        ),
        migrations.AlterField(
            model_name='ensamfiltr',
            name='klassifikator',
            field=models.ManyToManyField(blank=True, null=True, to='minenergiya.klassifikator', verbose_name='klassifikator'),
        ),
        migrations.AlterField(
            model_name='ensamfiltr',
            name='tur',
            field=models.ManyToManyField(blank=True, null=True, to='minenergiya.tur', verbose_name='tur'),
        ),
    ]
