# Generated by Django 4.0.5 on 2022-10-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minenergiya', '0018_alter_ensamfiltr_options_remove_ensamfiltr_vaqt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensamfiltr',
            name='sana',
        ),
        migrations.AddField(
            model_name='ensamfiltr',
            name='vaqt',
            field=models.DateTimeField(default=1, verbose_name='Vaqti'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ensamfiltr',
            name='filtr_faqir',
            field=models.ManyToManyField(blank=True, to='minenergiya.filtr_faqir', verbose_name='Foydalanuvchilar'),
        ),
        migrations.AlterField(
            model_name='ensamfiltr',
            name='guruh',
            field=models.ManyToManyField(blank=True, to='minenergiya.guruh', verbose_name='Guruhlar'),
        ),
        migrations.AlterField(
            model_name='ensamfiltr',
            name='klassifikator',
            field=models.ManyToManyField(blank=True, to='minenergiya.klassifikator', verbose_name='klassifikator'),
        ),
        migrations.AlterField(
            model_name='ensamfiltr',
            name='tur',
            field=models.ManyToManyField(blank=True, to='minenergiya.tur', verbose_name='tur'),
        ),
    ]
