# Generated by Django 4.0.5 on 2022-10-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minenergiya', '0019_remove_ensamfiltr_sana_ensamfiltr_vaqt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensamfiltr',
            name='dan',
            field=models.DateField(blank=True, verbose_name='dan'),
        ),
        migrations.AlterField(
            model_name='ensamfiltr',
            name='gacha',
            field=models.DateField(blank=True, verbose_name='gacha'),
        ),
        migrations.AlterField(
            model_name='ensamfiltr',
            name='vaqt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vaqti'),
        ),
    ]
