# Generated by Django 4.0.5 on 2022-10-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minenergiya', '0020_alter_ensamfiltr_dan_alter_ensamfiltr_gacha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensamfiltr',
            name='dan',
            field=models.DateField(blank=True, null=True, verbose_name='dan'),
        ),
        migrations.AlterField(
            model_name='ensamfiltr',
            name='gacha',
            field=models.DateField(blank=True, null=True, verbose_name='gacha'),
        ),
        migrations.AlterField(
            model_name='ensamfiltr',
            name='olchov',
            field=models.TextField(blank=True, null=True, verbose_name='O`lchov birliklari'),
        ),
    ]
