# Generated by Django 4.0.5 on 2022-10-24 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0046_alter_resurslar_birlik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minenergiya', '0021_alter_ensamfiltr_dan_alter_ensamfiltr_gacha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='his_res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_ID', models.CharField(blank=True, max_length=50, unique=True, verbose_name='E_ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
                ('res', models.ManyToManyField(blank=True, to='s_ad.resurslar')),
            ],
            options={
                'verbose_name': 'hisobot resursi',
                'verbose_name_plural': 'hisobot resurslari',
            },
        ),
    ]
