# Generated by Django 4.0.5 on 2022-10-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minenergiya', '0022_his_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensamfiltr',
            name='E_ID',
            field=models.CharField(blank=True, max_length=50, verbose_name='E_ID'),
        ),
        migrations.AlterField(
            model_name='filtr_faqir',
            name='E_ID',
            field=models.CharField(blank=True, max_length=50, verbose_name='E_ID'),
        ),
        migrations.AlterField(
            model_name='guruh',
            name='E_ID',
            field=models.CharField(blank=True, max_length=50, verbose_name='E_ID'),
        ),
        migrations.AlterField(
            model_name='his_res',
            name='E_ID',
            field=models.CharField(blank=True, max_length=50, verbose_name='E_ID'),
        ),
        migrations.AlterField(
            model_name='klassifikator',
            name='E_ID',
            field=models.CharField(blank=True, max_length=50, verbose_name='E_ID'),
        ),
        migrations.AlterField(
            model_name='tur',
            name='E_ID',
            field=models.CharField(blank=True, max_length=50, verbose_name='E_ID'),
        ),
    ]
