# Generated by Django 4.0.5 on 2022-10-24 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0046_alter_resurslar_birlik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minenergiya', '0024_rename_res_his_res_resurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='his_res',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi'),
        ),
        migrations.RemoveField(
            model_name='his_res',
            name='resurs',
        ),
        migrations.AddField(
            model_name='his_res',
            name='resurs',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='s_ad.resurslar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='klassifikator',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi'),
        ),
        migrations.AlterField(
            model_name='tur',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi'),
        ),
    ]
