# Generated by Django 4.0.5 on 2022-10-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minenergiya', '0025_alter_his_res_owner_remove_his_res_resurs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensamfiltr',
            name='nomi',
            field=models.TextField(verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='guruh',
            name='nomi',
            field=models.TextField(verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='klassifikator',
            name='klass',
            field=models.TextField(verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='tur',
            name='tur',
            field=models.TextField(verbose_name='Turi'),
        ),
    ]
