# Generated by Django 4.0.5 on 2022-10-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minenergiya', '0026_alter_ensamfiltr_nomi_alter_guruh_nomi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensamfiltr',
            name='his_res',
            field=models.ManyToManyField(blank=True, to='minenergiya.his_res', verbose_name='tur'),
        ),
    ]
