# Generated by Django 4.0.5 on 2022-11-23 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minenergiya', '0028_ensamfiltr_shakl_michpar'),
    ]

    operations = [
        migrations.CreateModel(
            name='variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.TextField(verbose_name='Hajm')),
                ('qiymat', models.FloatField(verbose_name='Hajm')),
                ('fqirshow', models.BooleanField(verbose_name="Foydalanuvchiga to'ldirishi")),
            ],
            options={
                'verbose_name': 'variant',
                'verbose_name_plural': 'variantlar',
            },
        ),
        migrations.CreateModel(
            name='kriteriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.TextField(verbose_name='Hajm')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
                ('variantlar', models.ManyToManyField(to='minenergiya.variant', verbose_name='Kriteriyalar')),
            ],
            options={
                'verbose_name': 'kriteriya',
                'verbose_name_plural': 'kriteriyalar',
            },
        ),
    ]
