# Generated by Django 4.0.5 on 2022-11-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minenergiya', '0029_variant_kriteriya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kriteriya',
            name='variantlar',
        ),
        migrations.AddField(
            model_name='kriteriya',
            name='MB',
            field=models.FloatField(blank=True, null=True, verbose_name='Bajarilish bosqichlari'),
        ),
        migrations.AddField(
            model_name='kriteriya',
            name='TO',
            field=models.FloatField(blank=True, null=True, verbose_name="Takrorlanishlar oralig'i"),
        ),
        migrations.AddField(
            model_name='kriteriya',
            name='TS',
            field=models.FloatField(blank=True, null=True, verbose_name='Takrorlanishlar soni'),
        ),
        migrations.AddField(
            model_name='kriteriya',
            name='i0',
            field=models.FloatField(blank=True, null=True, verbose_name='Bajaruvchining kunlik ish haqqi'),
        ),
        migrations.AddField(
            model_name='kriteriya',
            name='tj',
            field=models.FloatField(blank=True, null=True, verbose_name='Bajarish uchun joriy ketgan vaqt'),
        ),
        migrations.AlterField(
            model_name='kriteriya',
            name='nomi',
            field=models.TextField(verbose_name='Savol'),
        ),
        migrations.DeleteModel(
            name='variant',
        ),
    ]
