# Generated by Django 4.0.5 on 2022-11-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minenergiya', '0030_remove_kriteriya_variantlar_kriteriya_mb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kriteriya',
            name='kp',
            field=models.FloatField(blank=True, null=True, verbose_name='Dasturga inson aralashuvi koeffitsiyenti'),
        ),
        migrations.AddField(
            model_name='kriteriya',
            name='tk',
            field=models.FloatField(blank=True, null=True, verbose_name='Dastur bajarish vaqti'),
        ),
    ]
