# Generated by Django 4.0.5 on 2022-11-23 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minenergiya', '0031_kriteriya_kp_kriteriya_tk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kriteriya',
            name='MB',
        ),
        migrations.RemoveField(
            model_name='kriteriya',
            name='TO',
        ),
        migrations.RemoveField(
            model_name='kriteriya',
            name='TS',
        ),
        migrations.RemoveField(
            model_name='kriteriya',
            name='i0',
        ),
        migrations.RemoveField(
            model_name='kriteriya',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='kriteriya',
            name='tj',
        ),
        migrations.RemoveField(
            model_name='kriteriya',
            name='tk',
        ),
        migrations.CreateModel(
            name='ver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.TextField(verbose_name='Savol')),
                ('MB', models.FloatField(blank=True, null=True, verbose_name='Bajarilish bosqichlari')),
                ('TS', models.FloatField(blank=True, null=True, verbose_name='Takrorlanishlar soni')),
                ('TO', models.FloatField(blank=True, null=True, verbose_name="Takrorlanishlar oralig'i")),
                ('tj', models.FloatField(blank=True, null=True, verbose_name='Bajarish uchun joriy ketgan vaqt')),
                ('tk', models.FloatField(blank=True, null=True, verbose_name='Dastur bajarish vaqti')),
                ('i0', models.FloatField(blank=True, null=True, verbose_name='Bajaruvchining kunlik ish haqqi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'variant',
                'verbose_name_plural': 'variantlar',
            },
        ),
        migrations.AddField(
            model_name='kriteriya',
            name='ver',
            field=models.ManyToManyField(to='minenergiya.ver', verbose_name='Variantlar'),
        ),
    ]
