# Generated by Django 4.0.5 on 2022-11-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minenergiya', '0032_remove_kriteriya_mb_remove_kriteriya_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kriteriya',
            name='ver',
            field=models.ManyToManyField(blank=True, null=True, to='minenergiya.ver', verbose_name='Variantlar'),
        ),
        migrations.CreateModel(
            name='miqdorlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ichres', models.TextField(blank=True, null=True, verbose_name='Ishlab chiqarish resurslari miqdori')),
                ('istres', models.TextField(blank=True, null=True, verbose_name='Ishlab chiqarish resurslari miqdori')),
                ('sotres', models.TextField(blank=True, null=True, verbose_name='Ishlab chiqarish resurslari miqdori')),
                ('his', models.TextField(blank=True, null=True, verbose_name='Hisobotlar miqdori')),
                ('kp', models.FloatField(blank=True, null=True, verbose_name='Dasturga inson aralashuvi koeffitsiyenti')),
                ('ver', models.ManyToManyField(to='minenergiya.ver', verbose_name='Variantlar')),
            ],
            options={
                'verbose_name': 'kriteriya',
                'verbose_name_plural': 'kriteriyalar',
            },
        ),
    ]
