# Generated by Django 4.0.5 on 2022-12-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minenergiya', '0034_miqdorlar_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kriteriya',
            name='ver',
            field=models.ManyToManyField(blank=True, to='minenergiya.ver', verbose_name='Variantlar'),
        ),
        migrations.AlterField(
            model_name='miqdorlar',
            name='ver',
            field=models.ManyToManyField(blank=True, to='minenergiya.ver', verbose_name='Variantlar'),
        ),
    ]
