# Generated by Django 4.0.1 on 2022-01-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sahifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Sarlavha')),
                ('permalink', models.CharField(max_length=12, unique=True, verbose_name='link')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Yangilanish sanasi')),
                ('bodytext', models.TextField(blank=True, verbose_name='Asosiy qism teksti')),
            ],
            options={
                'verbose_name': 'sahifa',
                'verbose_name_plural': 'sahifalar',
            },
        ),
    ]
