# Generated by Django 4.0.1 on 2022-01-10 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_ad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davlatlar',
            name='davlat_nomi',
            field=models.TextField(verbose_name='Davlat nomi'),
        ),
        migrations.CreateModel(
            name='viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat_davlati', models.CharField(max_length=100, verbose_name='Viloyat joylashgan davlat')),
                ('viloyat_kodi', models.IntegerField(verbose_name='Viloyat kodi')),
                ('viloyat_nomi', models.CharField(max_length=100, verbose_name='Viloyat nomi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '02_Viloyatlar',
            },
        ),
    ]
