# Generated by Django 4.0.1 on 2022-01-10 18:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_ad', '0002_alter_davlatlar_davlat_nomi_viloyat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='viloyat',
            new_name='viloyatlar',
        ),
    ]
