# Generated by Django 4.0.1 on 2022-01-10 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_ad', '0003_rename_viloyat_viloyatlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuman_davlati', models.CharField(max_length=100, verbose_name='Tuman/shahar joylashgan davlat')),
                ('tuman_viloyati', models.CharField(max_length=100, verbose_name='Tuman/shahar joylashgan viloyat')),
                ('tuman_kodi', models.IntegerField(verbose_name='Tuman/shahar kodi')),
                ('tuman_nomi', models.CharField(max_length=100, verbose_name='Tuman/shahar nomi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '03_Tumanlar',
            },
        ),
    ]
