# Generated by Django 4.0.1 on 2022-01-11 02:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_ad', '0004_tuman'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tuman',
            new_name='tumanlar',
        ),
    ]
