# Generated by Django 4.0.1 on 2022-01-11 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0006_city_country_person_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viloyatlar',
            name='viloyat_davlati',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_ad.davlatlar'),
        ),
    ]
