# Generated by Django 4.0.1 on 2022-01-11 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0007_alter_viloyatlar_viloyat_davlati'),
    ]

    operations = [
        migrations.AddField(
            model_name='viloyatlar',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='s_ad.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viloyatlar',
            name='viloyat_davlati',
            field=models.CharField(max_length=100, verbose_name='Viloyat joylashgan davlat'),
        ),
    ]
