# Generated by Django 4.0.1 on 2022-01-11 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0008_viloyatlar_country_alter_viloyatlar_viloyat_davlati'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viloyatlar',
            name='country',
        ),
    ]
