# Generated by Django 4.0.1 on 2022-01-11 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_ad', '0009_remove_viloyatlar_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='viloyatcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat_davlati', models.CharField(max_length=100, verbose_name='Viloyat joylashgan davlat')),
                ('viloyat_kodi', models.IntegerField(verbose_name='Viloyat kodi')),
                ('viloyat_nomi', models.CharField(max_length=100, verbose_name='Viloyat nomi')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_ad.country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '02_Viloyatlar',
            },
        ),
    ]
