# Generated by Django 4.0.1 on 2022-01-11 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0010_viloyatcha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='viloyatlar',
        ),
    ]
