# Generated by Django 4.0.1 on 2022-01-11 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0013_alter_tumanlar_tuman_davlati_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tumanlar',
        ),
    ]
