# Generated by Django 4.0.1 on 2022-01-11 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_ad', '0014_delete_tumanlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='tumanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuman_kodi', models.IntegerField(verbose_name='Tuman/shahar kodi')),
                ('tuman_nomi', models.CharField(max_length=100, verbose_name='Tuman/shahar nomi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tuman_davlati', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='s_ad.davlatlar')),
                ('tuman_viloyati', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='s_ad.viloyatlar')),
            ],
            options={
                'verbose_name_plural': '03_Tumanlar',
            },
        ),
    ]
