# Generated by Django 4.0.1 on 2022-01-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0015_tumanlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tumanlar',
            name='tuman_davlati',
            field=models.CharField(default=1, max_length=100, verbose_name='Tuman/shahar joylashgan davlat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tumanlar',
            name='tuman_viloyati',
            field=models.CharField(default=2, max_length=100, verbose_name='Tuman/shahar joylashgan viloyat'),
            preserve_default=False,
        ),
    ]
