# Generated by Django 4.0.1 on 2022-01-11 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0016_alter_tumanlar_tuman_davlati_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tumanlar',
            name='tuman_davlati',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='s_ad.davlatlar'),
        ),
        migrations.AlterField(
            model_name='tumanlar',
            name='tuman_viloyati',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='s_ad.viloyatlar'),
        ),
    ]
