# Generated by Django 4.0.1 on 2022-01-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0017_alter_tumanlar_tuman_davlati_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tumanlar',
            name='tuman_davlati',
            field=models.CharField(default=1, max_length=100, verbose_name='Tuman/shahar nomi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tumanlar',
            name='tuman_viloyati',
            field=models.CharField(max_length=100, verbose_name='Tuman/shahar nomi'),
        ),
        migrations.AlterField(
            model_name='viloyatlar',
            name='viloyat_davlati',
            field=models.CharField(max_length=50, verbose_name='Viloyat davlati'),
        ),
    ]
