# Generated by Django 4.0.1 on 2022-01-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0018_alter_tumanlar_tuman_davlati_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
