# Generated by Django 4.0.1 on 2022-01-11 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_ad', '0019_remove_person_city_remove_person_country_delete_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IFTUM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolim', models.CharField(max_length=2, verbose_name='Bo`lim')),
                ('bob', models.IntegerField(verbose_name='Bob')),
                ('guruh', models.IntegerField(verbose_name='Guruh')),
                ('sinf', models.IntegerField(verbose_name='Sinf')),
                ('tartib', models.IntegerField(verbose_name='Tartib')),
                ('nomi', models.TextField(unique=True, verbose_name='IFTUM nomi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '04_IFTUM kodi',
            },
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
