# Generated by Django 4.0.1 on 2022-01-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0021_dbibt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbibt',
            name='dbibt',
            field=models.CharField(max_length=15, verbose_name='KTUT kodi'),
        ),
        migrations.AlterField(
            model_name='dbibt',
            name='ktut',
            field=models.CharField(max_length=15, verbose_name='KTUT kodi'),
        ),
    ]
