# Generated by Django 4.0.1 on 2022-01-11 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_ad', '0022_alter_dbibt_dbibt_alter_dbibt_ktut'),
    ]

    operations = [
        migrations.CreateModel(
            name='THST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thst', models.CharField(max_length=15, verbose_name='KTUT kodi')),
                ('nomi', models.TextField(unique=True, verbose_name='DBIBT nomi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '05_DBIBT kodi',
            },
        ),
    ]
