# Generated by Django 4.0.1 on 2022-01-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0023_thst'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thst',
            options={'verbose_name_plural': '06_THShT kodi'},
        ),
        migrations.RemoveField(
            model_name='thst',
            name='thst',
        ),
        migrations.AddField(
            model_name='thst',
            name='bolim',
            field=models.CharField(default=1, max_length=15, verbose_name='Klassifikator bo`limi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thst',
            name='tur',
            field=models.CharField(default=1, max_length=15, verbose_name='Klassifikator bo`limi'),
            preserve_default=False,
        ),
    ]
