# Generated by Django 4.0.1 on 2022-01-12 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_ad', '0024_alter_thst_options_remove_thst_thst_thst_bolim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='resurslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50, verbose_name='Kattalik nomi')),
                ('birlik', models.CharField(max_length=20, verbose_name='Kattalik birligi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '08_Resurslar',
            },
        ),
        migrations.CreateModel(
            name='birliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birlik', models.CharField(max_length=20, verbose_name='Birlik')),
                ('asos', models.CharField(max_length=20, verbose_name='Asosi')),
                ('farq', models.FloatField(verbose_name='Farq')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '07_Birliklar',
            },
        ),
    ]
