# Generated by Django 4.0.1 on 2022-01-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0025_resurslar_birliklar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davlatlar',
            name='davlat_kodi',
            field=models.IntegerField(unique=True, verbose_name='Davlat kodi'),
        ),
        migrations.AlterField(
            model_name='davlatlar',
            name='davlat_nomi',
            field=models.TextField(unique=True, verbose_name='Davlat nomi'),
        ),
        migrations.AlterField(
            model_name='resurslar',
            name='birlik',
            field=models.CharField(max_length=20, verbose_name='Resurs birligi'),
        ),
        migrations.AlterField(
            model_name='resurslar',
            name='nomi',
            field=models.CharField(max_length=50, verbose_name='Resurs nomi'),
        ),
        migrations.AlterField(
            model_name='viloyatlar',
            name='viloyat_kodi',
            field=models.FloatField(verbose_name='Tuman kodi'),
        ),
    ]
