# Generated by Django 4.0.1 on 2022-01-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0026_alter_davlatlar_davlat_kodi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resurslar',
            name='nomi',
            field=models.TextField(verbose_name='Resurs nomi'),
        ),
    ]
