# Generated by Django 4.0.1 on 2022-01-26 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_ad', '0027_alter_resurslar_nomi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valyuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='Nomi')),
                ('somda', models.FloatField(blank=True, max_length=20, verbose_name='Necha so`mi')),
                ('qiymati', models.FloatField(blank=True, verbose_name='Qancha valyuta')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valyuta',
                'verbose_name_plural': '09_Valyutalar',
            },
        ),
    ]
