# Generated by Django 4.0.1 on 2022-01-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0028_valyuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='valyuta',
            name='checker',
            field=models.BooleanField(default=1, verbose_name='Tekshirish'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='valyuta',
            name='qiymati',
            field=models.FloatField(blank=True, default=0, verbose_name='Qancha valyuta'),
        ),
        migrations.AlterField(
            model_name='valyuta',
            name='somda',
            field=models.FloatField(blank=True, default=0, verbose_name='Necha so`mi'),
        ),
    ]
