# Generated by Django 4.0.1 on 2022-01-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0029_valyuta_checker_alter_valyuta_qiymati_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valyuta',
            name='checker',
            field=models.BooleanField(blank=True, verbose_name='Tekshirish'),
        ),
    ]
