# Generated by Django 4.0.1 on 2022-01-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0031_resurslar_fkal_resurslar_gj_resurslar_tne_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resurslar',
            old_name='fkal',
            new_name='Gkal',
        ),
    ]
