# Generated by Django 4.0.1 on 2022-01-26 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0032_rename_fkal_resurslar_gkal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resurslar',
            old_name='Gkal',
            new_name='gkal',
        ),
    ]
