# Generated by Django 4.0.1 on 2022-01-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0033_rename_gkal_resurslar_gkal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resurslar',
            name='gj',
            field=models.FloatField(blank=True, default=0.0, verbose_name='GJ'),
        ),
        migrations.AlterField(
            model_name='resurslar',
            name='gkal',
            field=models.FloatField(blank=True, default=0.0, verbose_name='GKAL'),
        ),
    ]
