# Generated by Django 3.2.12 on 2022-02-09 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0034_alter_resurslar_gj_alter_resurslar_gkal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tumanlar',
            name='tuman_davlati',
        ),
        migrations.AlterField(
            model_name='tumanlar',
            name='tuman_viloyati',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_ad.viloyatlar'),
        ),
        migrations.AlterField(
            model_name='viloyatlar',
            name='viloyat_davlati',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_ad.davlatlar'),
        ),
    ]
