# Generated by Django 3.2.12 on 2022-02-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0035_auto_20220209_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viloyatlar',
            name='viloyat_kodi',
            field=models.FloatField(verbose_name='Viloyat kodi'),
        ),
    ]
