# Generated by Django 4.0.5 on 2022-09-17 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_ad', '0036_alter_viloyatlar_viloyat_kodi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tadbir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodi', models.IntegerField(verbose_name='Tadbir kodi')),
                ('nomi', models.TextField(verbose_name='Tadbir nomi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': 'Tadbirlar',
            },
        ),
    ]
