# Generated by Django 4.0.5 on 2022-09-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0037_tadbir'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tadbir',
            options={'verbose_name': 'Tadbir', 'verbose_name_plural': '10_Tadbirlar'},
        ),
    ]
