# Generated by Django 4.0.5 on 2022-10-21 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_ad', '0038_alter_tadbir_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='yaxlitlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asos', models.CharField(max_length=50, verbose_name='Nomi')),
                ('farq', models.FloatField(verbose_name='Qiymati')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '07_Yaxlitlash qiymatlari',
            },
        ),
    ]
