# Generated by Django 4.0.5 on 2022-10-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0039_yaxlitlash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yaxlitlash',
            name='asos',
        ),
        migrations.AddField(
            model_name='yaxlitlash',
            name='nomi',
            field=models.CharField(default=1, max_length=50, verbose_name='Nomi'),
            preserve_default=False,
        ),
    ]
