# Generated by Django 4.0.5 on 2022-10-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0040_remove_yaxlitlash_asos_yaxlitlash_nomi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yaxlitlash',
            old_name='farq',
            new_name='qiymati',
        ),
        migrations.AddField(
            model_name='yaxlitlash',
            name='checker',
            field=models.BooleanField(blank=True, default=1, verbose_name='Tekshirish'),
            preserve_default=False,
        ),
    ]
