# Generated by Django 4.0.5 on 2022-10-21 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0041_rename_farq_yaxlitlash_qiymati_yaxlitlash_checker'),
    ]

    operations = [
        migrations.AddField(
            model_name='resurslar',
            name='yaxlitlash',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='s_ad.yaxlitlash'),
            preserve_default=False,
        ),
    ]
