# Generated by Django 4.0.5 on 2022-10-21 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0042_resurslar_yaxlitlash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resurslar',
            name='yaxlitlash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.yaxlitlash'),
        ),
    ]
