# Generated by Django 4.0.5 on 2022-10-21 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0043_alter_resurslar_yaxlitlash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resurslar',
            name='yaxlitlash',
        ),
    ]
