# Generated by Django 4.0.5 on 2022-10-21 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0045_resurslar_yaxlit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resurslar',
            name='birlik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.birliklar'),
        ),
    ]
