# Generated by Django 4.0.5 on 2022-11-16 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_ad', '0046_alter_resurslar_birlik'),
    ]

    operations = [
        migrations.CreateModel(
            name='res_maqsad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.TextField(verbose_name='Tadbir nomi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resurs maqsad',
                'verbose_name_plural': 'Resursni ishlatish maqsadlari',
            },
        ),
    ]
