# Generated by Django 4.0.5 on 2022-11-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0047_res_maqsad'),
    ]

    operations = [
        migrations.AddField(
            model_name='res_maqsad',
            name='checker',
            field=models.BooleanField(default=1, verbose_name='Checker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='res_maqsad',
            name='ich',
            field=models.BooleanField(default=1, verbose_name='Ishlab chiqarish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='res_maqsad',
            name='ist',
            field=models.BooleanField(default=1, verbose_name="Iste'mol"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='res_maqsad',
            name='sot',
            field=models.BooleanField(default=1, verbose_name='Sotish/uzat'),
            preserve_default=False,
        ),
    ]
