# Generated by Django 4.0.5 on 2022-11-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0048_res_maqsad_checker_res_maqsad_ich_res_maqsad_ist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='res_maqsad',
            options={'verbose_name': 'Resurs maqsad', 'verbose_name_plural': '11_Resursni ishlatish maqsadlari'},
        ),
        migrations.AlterField(
            model_name='res_maqsad',
            name='checker',
            field=models.BooleanField(null=True, verbose_name='Checker'),
        ),
        migrations.AlterField(
            model_name='res_maqsad',
            name='ich',
            field=models.BooleanField(default=False, verbose_name='Ishlab chiqarish'),
        ),
        migrations.AlterField(
            model_name='res_maqsad',
            name='ist',
            field=models.BooleanField(default=False, verbose_name="Iste'mol"),
        ),
        migrations.AlterField(
            model_name='res_maqsad',
            name='nomi',
            field=models.TextField(verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='res_maqsad',
            name='sot',
            field=models.BooleanField(default=False, verbose_name='Sotish/uzat'),
        ),
    ]
