# Generated by Django 4.0.5 on 2022-11-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0049_alter_res_maqsad_options_alter_res_maqsad_checker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resurslar',
            name='yaxlit',
        ),
    ]
