# Generated by Django 4.0.5 on 2022-11-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0050_remove_resurslar_yaxlit'),
    ]

    operations = [
        migrations.AddField(
            model_name='resurslar',
            name='aktiv',
            field=models.BooleanField(default=1, verbose_name='Aktiv'),
            preserve_default=False,
        ),
    ]
