# Generated by Django 4.0.5 on 2022-11-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0052_elon'),
    ]

    operations = [
        migrations.AddField(
            model_name='elon',
            name='oqildi',
            field=models.BooleanField(default=1, verbose_name="O'qildi"),
            preserve_default=False,
        ),
    ]
