# Generated by Django 4.0.5 on 2022-11-18 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_ad', '0053_elon_oqildi'),
    ]

    operations = [
        migrations.AddField(
            model_name='elon',
            name='dan',
            field=models.IntegerField(default=1, verbose_name='dan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elon',
            name='ga',
            field=models.IntegerField(default=1, verbose_name='ga'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elon',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
