# Generated by Django 4.0.5 on 2022-11-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0054_elon_dan_elon_ga_elon_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elon',
            name='url',
            field=models.TextField(max_length=200, verbose_name='url'),
        ),
    ]
