# Generated by Django 4.0.5 on 2022-11-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0055_alter_elon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='elon',
            name='javob',
            field=models.TextField(default=1, verbose_name='Javob'),
            preserve_default=False,
        ),
    ]
