# Generated by Django 4.0.5 on 2022-11-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0056_elon_javob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elon',
            name='javob',
            field=models.TextField(blank=True, verbose_name='Javob'),
        ),
    ]
