# Generated by Django 4.0.5 on 2022-11-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0057_alter_elon_javob'),
    ]

    operations = [
        migrations.AddField(
            model_name='elon',
            name='jb',
            field=models.BooleanField(default=1, verbose_name='Javob bor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elon',
            name='jb_oqildi',
            field=models.BooleanField(default=1, verbose_name="Javob o'qildi"),
            preserve_default=False,
        ),
    ]
