# Generated by Django 4.0.5 on 2022-11-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0058_elon_jb_elon_jb_oqildi'),
    ]

    operations = [
        migrations.AddField(
            model_name='elon',
            name='masala',
            field=models.TextField(blank=True, null=True, verbose_name='masala'),
        ),
    ]
