# Generated by Django 4.0.5 on 2022-11-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0062_alter_elon_masala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elon',
            name='jbvaqt',
            field=models.DateTimeField(null=True, verbose_name='Javob vaqti'),
        ),
    ]
