# Generated by Django 4.0.5 on 2022-11-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0064_alter_elon_masala'),
    ]

    operations = [
        migrations.AddField(
            model_name='birliklar',
            name='aktiv',
            field=models.BooleanField(default=1, verbose_name='Aktiv'),
            preserve_default=False,
        ),
    ]
