# Generated by Django 4.0.5 on 2022-11-19 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0065_birliklar_aktiv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elon',
            name='masala',
        ),
        migrations.AddField(
            model_name='elon',
            name='birlik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.birliklar', verbose_name='Birilik'),
        ),
        migrations.AddField(
            model_name='elon',
            name='hajm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.yaxlitlash', verbose_name='Hajm'),
        ),
        migrations.AddField(
            model_name='elon',
            name='maqsad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.res_maqsad', verbose_name='Maqsad'),
        ),
        migrations.AddField(
            model_name='elon',
            name='resurs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.resurslar', verbose_name='Resurslar'),
        ),
    ]
