# Generated by Django 4.0.1 on 2022-01-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahifa',
            name='icon',
            field=models.CharField(default=1, max_length=30, verbose_name='Icon nomi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sahifa',
            name='permalink',
            field=models.CharField(max_length=12, unique=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='sahifa',
            name='update_date',
            field=models.DateTimeField(verbose_name='Yangilanish sanasi'),
        ),
    ]
