# Generated by Django 4.0.1 on 2022-01-08 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kirish', '0002_sahifa_icon_alter_sahifa_permalink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahifa',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
