# Generated by Django 4.0.1 on 2022-01-10 04:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kirish', '0003_sahifa_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sahifa',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 4, 18, 51, 736616, tzinfo=utc), verbose_name='Yangilanish sanasi'),
        ),
    ]
