# Generated by Django 4.0.1 on 2022-01-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirish', '0004_alter_sahifa_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sahifa',
            name='update_date',
            field=models.DateTimeField(verbose_name='Yangilanish sanasi'),
        ),
    ]
