# Generated by Django 4.0.1 on 2022-01-20 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kirish', '0005_alter_sahifa_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='savolnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol1', models.BooleanField(verbose_name='Ishlab chiqarish/servis mavjudmi?')),
                ('savol2', models.BooleanField(verbose_name='Uzatish mavjudmi?')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'savolnoma',
                'verbose_name_plural': '02_savolnomalar',
            },
        ),
    ]
