# Generated by Django 4.0.1 on 2022-01-20 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kirish', '0006_savolnoma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sahifa',
            options={'verbose_name': 'sahifa', 'verbose_name_plural': '01_sahifalar'},
        ),
        migrations.AlterField(
            model_name='savolnoma',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
