# Generated by Django 4.0.5 on 2023-02-28 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Til',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.TextField(verbose_name='Jumla')),
                ('vaqt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Vaqti')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'Til',
                'verbose_name_plural': 'Tils',
            },
        ),
        migrations.CreateModel(
            name='Tarjima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.TextField(verbose_name='Tarjima')),
                ('vaqt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Vaqti')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
                ('til', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarjimon.til', verbose_name='Tili')),
            ],
            options={
                'verbose_name': 'Tarjima',
                'verbose_name_plural': '02_Tarjimalar',
            },
        ),
        migrations.CreateModel(
            name='jumla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.TextField(verbose_name='Jumla')),
                ('vaqt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='01_Vaqti')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
                ('tarjimasi', models.ManyToManyField(blank=True, to='tarjimon.tarjima', verbose_name='Foydalanuvchilar')),
            ],
            options={
                'verbose_name': 'jumla',
                'verbose_name_plural': '01_jumlas',
            },
        ),
    ]
