# Generated by Django 4.0.5 on 2023-02-28 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarjimon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jumla',
            options={'verbose_name': 'jumla', 'verbose_name_plural': '01_jumlalar'},
        ),
        migrations.AlterModelOptions(
            name='til',
            options={'verbose_name': 'Til', 'verbose_name_plural': 'Tillar'},
        ),
        migrations.RemoveField(
            model_name='jumla',
            name='tarjimasi',
        ),
        migrations.CreateModel(
            name='Tarjimon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarjimon.jumla', verbose_name='Jumla')),
                ('tarjimasi', models.ManyToManyField(blank=True, to='tarjimon.tarjima', verbose_name='Tarjimalari')),
            ],
            options={
                'verbose_name': 'Tarjimon',
                'verbose_name_plural': '04_Tarjimon',
            },
        ),
    ]
