# Generated by Django 4.0.5 on 2023-02-28 03:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarjimon', '0002_alter_jumla_options_alter_til_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjima',
            options={'verbose_name': 'Tarjima', 'verbose_name_plural': '03_Tarjimalar'},
        ),
        migrations.AlterModelOptions(
            name='til',
            options={'verbose_name': 'Til', 'verbose_name_plural': '02_Tillar'},
        ),
        migrations.RemoveField(
            model_name='til',
            name='owner',
        ),
        migrations.AddField(
            model_name='til',
            name='tarjimonlar',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Tarjimonlar'),
        ),
    ]
