# Generated by Django 4.0.5 on 2023-02-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjimon', '0003_alter_tarjima_options_alter_til_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='til',
            name='bayroq',
            field=models.ImageField(blank=True, max_length=255, upload_to='bayroq', verbose_name='Bayroq'),
        ),
    ]
