# Generated by Django 4.0.5 on 2023-03-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjimon', '0004_til_bayroq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='til',
            name='bayroq',
            field=models.ImageField(blank=True, default='profile_emb/login_emb.jpg', max_length=255, upload_to='bayroq', verbose_name='Bayroq'),
        ),
    ]
