# Generated by Django 4.0.1 on 2022-01-13 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ichres',
            options={'verbose_name_plural': 'Ishlab chiqarish resurslari'},
        ),
        migrations.RenameField(
            model_name='ichres',
            old_name='nomi',
            new_name='nom',
        ),
    ]
