# Generated by Django 4.0.1 on 2022-01-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0002_alter_ichres_options_rename_nomi_ichres_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='ichres',
            name='birlik',
            field=models.CharField(default=1, max_length=100, verbose_name='Resurs birligi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ichres',
            name='nom',
            field=models.CharField(default=1, max_length=100, verbose_name='Resurs nomi'),
            preserve_default=False,
        ),
    ]
