# Generated by Django 4.0.1 on 2022-01-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0003_ichres_birlik_alter_ichres_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ichres',
            name='nom',
            field=models.TextField(max_length=100, verbose_name='Resurs nomi'),
        ),
    ]
