# Generated by Django 4.0.1 on 2022-01-15 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0005_alter_ichres_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='sotres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=100, unique=True, verbose_name='Resurs nomi')),
                ('birlik', models.CharField(max_length=100, verbose_name='Resurs birligi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ishlab chiqarish resurslari',
            },
        ),
        migrations.CreateModel(
            name='istres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=100, unique=True, verbose_name='Resurs nomi')),
                ('birlik', models.CharField(max_length=100, verbose_name='Resurs birligi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ishlab chiqarish resurslari',
            },
        ),
    ]
