# Generated by Django 4.0.1 on 2022-01-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0006_sotres_istres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='istres',
            options={'verbose_name_plural': 'Iste`mol resurslari'},
        ),
        migrations.AlterModelOptions(
            name='sotres',
            options={'verbose_name_plural': 'Sotiladigan resurslar'},
        ),
    ]
