# Generated by Django 4.0.1 on 2022-01-17 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0008_davrich'),
    ]

    operations = [
        migrations.CreateModel(
            name='HisobotClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yartilgan_sana', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ResursClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HisobotResursClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hisobot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foydalanuvchi.hisobotclass')),
                ('resurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foydalanuvchi.resursclass')),
            ],
        ),
        migrations.AddField(
            model_name='hisobotclass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foydalanuvchi.userclass'),
        ),
    ]
