# Generated by Django 4.0.1 on 2022-01-17 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0027_alter_resurslar_nomi'),
        ('foydalanuvchi', '0009_hisobotclass_resursclass_userclass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sotres',
            name='birlik',
        ),
        migrations.RemoveField(
            model_name='sotres',
            name='nom',
        ),
        migrations.AddField(
            model_name='sotres',
            name='resurs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='s_ad.resurslar'),
            preserve_default=False,
        ),
    ]
