# Generated by Django 4.0.1 on 2022-01-17 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0027_alter_resurslar_nomi'),
        ('foydalanuvchi', '0012_remove_sotres_birlik_remove_sotres_nom_sotres_resurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotres',
            name='resurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_ad.resurslar', unique=True),
        ),
    ]
