# Generated by Django 4.0.1 on 2022-01-17 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0013_alter_sotres_resurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='hisobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('vaqt', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'hisobot',
                'verbose_name_plural': 'hisobotlar',
            },
        ),
        migrations.CreateModel(
            name='hisobot_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qiymat', models.FloatField(verbose_name='qiymat')),
                ('hisobot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foydalanuvchi.hisobot')),
                ('sotres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foydalanuvchi.sotres', unique=True)),
            ],
        ),
    ]
