# Generated by Django 4.0.1 on 2022-01-18 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0016_remove_hisobot_item_resurs_hisobot_item_sotres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisobot',
            name='vaqt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hisobot_item',
            name='sotres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foydalanuvchi.sotres'),
        ),
    ]
