# Generated by Django 4.0.1 on 2022-01-18 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0017_alter_hisobot_vaqt_alter_hisobot_item_sotres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hisobot_item',
            old_name='hisobot',
            new_name='hisobot1',
        ),
    ]
