# Generated by Django 4.0.1 on 2022-01-18 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0018_rename_hisobot_hisobot_item_hisobot1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hisobot_item',
            old_name='sotres',
            new_name='sotres1',
        ),
    ]
