# Generated by Django 4.0.1 on 2022-01-18 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0019_rename_sotres_hisobot_item_sotres1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hisobot_item',
            old_name='hisobot1',
            new_name='hisobot',
        ),
        migrations.RenameField(
            model_name='hisobot_item',
            old_name='sotres1',
            new_name='sotres',
        ),
    ]
