# Generated by Django 4.0.1 on 2022-01-19 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0027_alter_resurslar_nomi'),
        ('foydalanuvchi', '0020_rename_hisobot1_hisobot_item_hisobot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotres',
            name='resurs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='s_ad.resurslar'),
        ),
    ]
