# Generated by Django 4.0.1 on 2022-01-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0021_alter_sotres_resurs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hisobotresursclass',
            name='hisobot',
        ),
        migrations.RemoveField(
            model_name='hisobotresursclass',
            name='resurs',
        ),
        migrations.DeleteModel(
            name='HisobotClass',
        ),
        migrations.DeleteModel(
            name='HisobotResursClass',
        ),
        migrations.DeleteModel(
            name='ResursClass',
        ),
        migrations.DeleteModel(
            name='UserClass',
        ),
    ]
