# Generated by Django 4.0.1 on 2022-01-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0022_remove_hisobotresursclass_hisobot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sotres',
            name='resurs',
        ),
        migrations.AddField(
            model_name='sotres',
            name='birlik',
            field=models.CharField(default=1, max_length=100, verbose_name='Resurs birligi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sotres',
            name='nom',
            field=models.TextField(default=1, max_length=100, unique=True, verbose_name='Resurs nomi'),
            preserve_default=False,
        ),
    ]
