# Generated by Django 4.0.1 on 2022-01-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0023_remove_sotres_resurs_sotres_birlik_sotres_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='hisobot',
            name='birlik',
            field=models.CharField(default=1, max_length=100, verbose_name='Resurs birligi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hisobot',
            name='nom',
            field=models.TextField(default=1, max_length=100, unique=True, verbose_name='Resurs nomi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hisobot',
            name='qiymat',
            field=models.FloatField(default=1, verbose_name='Resurs qiymati'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hisobot',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Hisobot nomi'),
        ),
        migrations.AlterField(
            model_name='hisobot',
            name='vaqt',
            field=models.DateTimeField(verbose_name='Hisobot vaqti'),
        ),
    ]
