# Generated by Django 4.0.1 on 2022-01-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0024_hisobot_birlik_hisobot_nom_hisobot_qiymat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisobot',
            name='nom',
            field=models.TextField(unique=True, verbose_name='Resurs nomi'),
        ),
    ]
