# Generated by Django 4.0.1 on 2022-01-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0025_alter_hisobot_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisobot',
            name='vaqt',
            field=models.DateTimeField(auto_now=True, verbose_name='Hisobot vaqti'),
        ),
    ]
