# Generated by Django 4.0.1 on 2022-01-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0026_alter_hisobot_vaqt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hisobot_item',
            name='hisobot',
        ),
        migrations.RemoveField(
            model_name='hisobot_item',
            name='qiymat',
        ),
        migrations.RemoveField(
            model_name='hisobot_item',
            name='sotres',
        ),
        migrations.AddField(
            model_name='hisobot_item',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Hisobot nomi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hisobot_item',
            name='vaqt',
            field=models.DateTimeField(auto_now=True, verbose_name='Vaqti'),
        ),
        migrations.AlterField(
            model_name='hisobot',
            name='vaqt',
            field=models.DateTimeField(auto_now=True, verbose_name='Vaqti'),
        ),
    ]
