# Generated by Django 4.0.1 on 2022-01-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0028_hisobot_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisobot',
            name='birlik',
            field=models.TextField(max_length=100, verbose_name='Resurs birligi'),
        ),
    ]
