# Generated by Django 4.0.1 on 2022-01-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0029_alter_hisobot_birlik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisobot',
            name='birlik',
            field=models.TextField(verbose_name='Resurs birligi'),
        ),
    ]
