# Generated by Django 4.0.1 on 2022-01-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0030_alter_hisobot_birlik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisobot',
            name='nom',
            field=models.TextField(verbose_name='Resurs nomi'),
        ),
    ]
