# Generated by Django 4.0.1 on 2022-01-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0031_alter_hisobot_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='hisobot',
            name='qiymat_pul',
            field=models.FloatField(default=1, verbose_name='Resurs qiymati'),
            preserve_default=False,
        ),
    ]
