# Generated by Django 4.0.1 on 2022-01-19 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0032_hisobot_qiymat_pul'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hisobot',
            new_name='hisobot_ich',
        ),
        migrations.CreateModel(
            name='hisobot_uzat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Hisobot nomi')),
                ('vaqt', models.DateTimeField(auto_now=True, verbose_name='Vaqti')),
                ('nom', models.TextField(verbose_name='Resurs nomi')),
                ('birlik', models.TextField(verbose_name='Resurs birligi')),
                ('qiymat', models.FloatField(verbose_name='Resurs qiymati')),
                ('qiymat_pul', models.FloatField(verbose_name='Resurs qiymati')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'hisobot',
                'verbose_name_plural': 'hisobotlar',
            },
        ),
        migrations.CreateModel(
            name='hisobot_ist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Hisobot nomi')),
                ('vaqt', models.DateTimeField(auto_now=True, verbose_name='Vaqti')),
                ('nom', models.TextField(verbose_name='Resurs nomi')),
                ('birlik', models.TextField(verbose_name='Resurs birligi')),
                ('qiymat', models.FloatField(verbose_name='Resurs qiymati')),
                ('qiymat_pul', models.FloatField(verbose_name='Resurs qiymati')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'hisobot',
                'verbose_name_plural': 'hisobotlar',
            },
        ),
    ]
