# Generated by Django 4.0.1 on 2022-01-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0033_rename_hisobot_hisobot_ich_hisobot_uzat_hisobot_ist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='davrich',
        ),
    ]
