# Generated by Django 4.0.1 on 2022-01-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0035_alter_hisobot_ich_options_alter_hisobot_ist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allfaqir',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': '03_Foydalanuvchilar'},
        ),
        migrations.AddField(
            model_name='allfaqir',
            name='admin',
            field=models.CharField(default=1, max_length=50, verbose_name='Boshqaruvchi nomi'),
            preserve_default=False,
        ),
    ]
