# Generated by Django 4.0.1 on 2022-01-20 07:09

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0036_alter_allfaqir_options_allfaqir_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfaqir',
            name='owner',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi'),
        ),
    ]
