# Generated by Django 4.0.1 on 2022-01-20 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0037_alter_allfaqir_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfaqir',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi'),
        ),
    ]
