# Generated by Django 4.0.1 on 2022-01-21 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0038_alter_allfaqir_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='his_ich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oraliq_min', models.CharField(max_length=50, verbose_name='Maksimal oraliq')),
                ('oraliq_max', models.CharField(max_length=50, verbose_name='Minimal oraliq')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
                ('resurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foydalanuvchi.hisobot_ich', verbose_name='Resurslar')),
            ],
            options={
                'verbose_name': 'Davriy hisobot',
                'verbose_name_plural': '04_Davriy hisobotlar',
            },
        ),
    ]
