# Generated by Django 4.0.1 on 2022-01-21 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0039_his_ich'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='his_ich',
            name='oraliq_max',
        ),
        migrations.RemoveField(
            model_name='his_ich',
            name='oraliq_min',
        ),
        migrations.AlterField(
            model_name='his_ich',
            name='resurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foydalanuvchi.ichres', verbose_name='Resurslar'),
        ),
        migrations.CreateModel(
            name='his_ich_vaqt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oraliq_min', models.CharField(max_length=50, verbose_name='Maksimal oraliq')),
                ('oraliq_max', models.CharField(max_length=50, verbose_name='Minimal oraliq')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'his_ich_vaqt',
                'verbose_name_plural': 'his_ich_vaqts',
            },
        ),
    ]
