# Generated by Django 4.0.1 on 2022-01-21 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0040_remove_his_ich_oraliq_max_remove_his_ich_oraliq_min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hisobot_full',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oraliq_min', models.CharField(max_length=50, verbose_name='Maksimal oraliq')),
                ('oraliq_max', models.CharField(max_length=50, verbose_name='Minimal oraliq')),
                ('hisobot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foydalanuvchi.his_ich', verbose_name='Hisobot resurslari')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'hisobot_full',
                'verbose_name_plural': '04_hisobot_full',
            },
        ),
        migrations.DeleteModel(
            name='his_ich_vaqt',
        ),
    ]
