# Generated by Django 4.0.1 on 2022-01-21 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0041_hisobot_full_delete_his_ich_vaqt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hisobot_full',
            options={'verbose_name': 'hisobot_full', 'verbose_name_plural': '04_1_hisobot_full'},
        ),
    ]
