# Generated by Django 4.0.1 on 2022-01-21 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0042_alter_hisobot_full_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='his_ich',
            options={'verbose_name': 'Davriy hisobot', 'verbose_name_plural': '04_0_Davriy hisobotlar'},
        ),
        migrations.RemoveField(
            model_name='hisobot_full',
            name='hisobot',
        ),
    ]
