# Generated by Django 4.0.1 on 2022-01-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0043_alter_his_ich_options_remove_hisobot_full_hisobot'),
    ]

    operations = [
        migrations.AddField(
            model_name='his_ich',
            name='nomi',
            field=models.CharField(default=1, max_length=50, verbose_name='Hisobot nomi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hisobot_full',
            name='nomi',
            field=models.CharField(default=1, max_length=50, verbose_name='Hisobot nomi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hisobot_full',
            name='vaqt',
            field=models.TimeField(auto_now=True, verbose_name='vaqt'),
        ),
    ]
