# Generated by Django 4.0.1 on 2022-01-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0044_his_ich_nomi_hisobot_full_nomi_hisobot_full_vaqt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisobot_full',
            name='vaqt',
            field=models.DateTimeField(auto_now=True, verbose_name='Vaqti'),
        ),
    ]
