# Generated by Django 4.0.1 on 2022-01-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0045_alter_hisobot_full_vaqt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='his_ich',
            name='resurs',
            field=models.CharField(max_length=50, verbose_name='Resurs'),
        ),
    ]
