# Generated by Django 4.0.1 on 2022-01-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0046_alter_his_ich_resurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='newclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'newclass',
                'verbose_name_plural': 'newclasss',
            },
        ),
        migrations.CreateModel(
            name='under_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'under_class',
                'verbose_name_plural': 'under_classs',
            },
        ),
        migrations.AlterModelOptions(
            name='allfaqir',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': '00_Foydalanuvchilar'},
        ),
    ]
