# Generated by Django 4.0.1 on 2022-01-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0047_newclass_under_class_alter_allfaqir_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newclass',
        ),
        migrations.DeleteModel(
            name='under_class',
        ),
        migrations.AddField(
            model_name='hisobot_full',
            name='resurs',
            field=models.TextField(default=1, verbose_name='Resurslar'),
            preserve_default=False,
        ),
    ]
