# Generated by Django 4.0.1 on 2022-01-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0048_delete_newclass_delete_under_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='manyfield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.ManyToManyField(to='foydalanuvchi.his_ich', verbose_name='manyfield')),
            ],
        ),
    ]
