# Generated by Django 4.0.1 on 2022-01-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0050_remove_hisobot_full_resurs_hisobot_full_resurs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hisobot_item',
            name='ich',
            field=models.ManyToManyField(to='foydalanuvchi.hisobot_ich', verbose_name='Ishlab chiqarish'),
        ),
        migrations.AddField(
            model_name='hisobot_item',
            name='ist',
            field=models.ManyToManyField(to='foydalanuvchi.hisobot_ist', verbose_name="Iste'mol"),
        ),
        migrations.AddField(
            model_name='hisobot_item',
            name='uzat',
            field=models.ManyToManyField(to='foydalanuvchi.hisobot_uzat', verbose_name='Uzatish/Sotish'),
        ),
    ]
