# Generated by Django 4.0.1 on 2022-01-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0051_hisobot_item_ich_hisobot_item_ist_hisobot_item_uzat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='his_ich',
            options={'verbose_name': 'Davriy hisobot', 'verbose_name_plural': '04_0_Ishlab chiqarish filteri'},
        ),
        migrations.AlterField(
            model_name='hisobot_full',
            name='resurs',
            field=models.ManyToManyField(to='foydalanuvchi.hisobot_ich', verbose_name='Resurslar'),
        ),
    ]
