# Generated by Django 4.0.1 on 2022-01-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0054_alter_hisobot_full_resurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisobot_full',
            name='resurs',
            field=models.ManyToManyField(to='foydalanuvchi.hisobot_item', verbose_name='Resurslar'),
        ),
    ]
