# Generated by Django 4.0.1 on 2022-01-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0055_alter_hisobot_full_resurs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hisobot_full',
            old_name='resurs',
            new_name='hisoborlar',
        ),
    ]
