# Generated by Django 4.0.1 on 2022-01-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0056_rename_resurs_hisobot_full_hisoborlar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hisobot_full',
            name='hisoborlar',
        ),
        migrations.AddField(
            model_name='hisobot_full',
            name='hisobotlar',
            field=models.ManyToManyField(to='foydalanuvchi.hisobot_item', verbose_name='Hisobotlar'),
        ),
    ]
