# Generated by Django 4.0.1 on 2022-01-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0057_remove_hisobot_full_hisoborlar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hisobot_full',
            name='Achart',
            field=models.BooleanField(default=1, verbose_name='A diagramma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hisobot_full',
            name='Chchart',
            field=models.BooleanField(default=1, verbose_name='CH diagramma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hisobot_full',
            name='Gchart',
            field=models.BooleanField(default=1, verbose_name='G diagramma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hisobot_full',
            name='Mchart',
            field=models.BooleanField(default=1, verbose_name='M diagramma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hisobot_full',
            name='Uchart',
            field=models.BooleanField(default=1, verbose_name='U diagramma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hisobot_full',
            name='Vchart',
            field=models.BooleanField(default=1, verbose_name='V diagramma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hisobot_full',
            name='dol',
            field=models.BooleanField(default=1, verbose_name='dollar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hisobot_full',
            name='gj',
            field=models.BooleanField(default=1, verbose_name='gj'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hisobot_full',
            name='kkal',
            field=models.BooleanField(default=1, verbose_name='kkal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hisobot_full',
            name='som',
            field=models.BooleanField(default=1, verbose_name="so'm"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hisobot_full',
            name='tne',
            field=models.BooleanField(default=1, verbose_name='tne'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hisobot_full',
            name='tshy',
            field=models.BooleanField(default=1, verbose_name='tshy'),
            preserve_default=False,
        ),
    ]
