# Generated by Django 4.0.1 on 2022-01-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0058_hisobot_full_achart_hisobot_full_chchart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hisobot_full',
            name='Achart',
        ),
        migrations.RemoveField(
            model_name='hisobot_full',
            name='Chchart',
        ),
        migrations.RemoveField(
            model_name='hisobot_full',
            name='Gchart',
        ),
        migrations.RemoveField(
            model_name='hisobot_full',
            name='Mchart',
        ),
        migrations.RemoveField(
            model_name='hisobot_full',
            name='Uchart',
        ),
        migrations.RemoveField(
            model_name='hisobot_full',
            name='Vchart',
        ),
        migrations.RemoveField(
            model_name='hisobot_full',
            name='dol',
        ),
        migrations.RemoveField(
            model_name='hisobot_full',
            name='gj',
        ),
        migrations.RemoveField(
            model_name='hisobot_full',
            name='kkal',
        ),
        migrations.RemoveField(
            model_name='hisobot_full',
            name='som',
        ),
        migrations.RemoveField(
            model_name='hisobot_full',
            name='tne',
        ),
        migrations.RemoveField(
            model_name='hisobot_full',
            name='tshy',
        ),
        migrations.AddField(
            model_name='hisobot_full',
            name='cheks',
            field=models.CharField(default=1, max_length=50, verbose_name='Chart va Birlik'),
            preserve_default=False,
        ),
    ]
