# Generated by Django 4.0.1 on 2022-01-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0059_remove_hisobot_full_achart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisobot_full',
            name='cheks',
            field=models.CharField(max_length=255, verbose_name='Chart va Birlik'),
        ),
        migrations.AlterField(
            model_name='hisobot_item',
            name='ich',
            field=models.ManyToManyField(blank=True, to='foydalanuvchi.hisobot_ich', verbose_name='Ishlab chiqarish'),
        ),
        migrations.AlterField(
            model_name='hisobot_item',
            name='ist',
            field=models.ManyToManyField(blank=True, to='foydalanuvchi.hisobot_ist', verbose_name="Iste'mol"),
        ),
        migrations.AlterField(
            model_name='hisobot_item',
            name='uzat',
            field=models.ManyToManyField(blank=True, to='foydalanuvchi.hisobot_uzat', verbose_name='Uzatish/Sotish'),
        ),
    ]
