# Generated by Django 4.0.1 on 2022-01-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0060_alter_hisobot_full_cheks_alter_hisobot_item_ich_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisobot_full',
            name='vaqt',
            field=models.DateTimeField(verbose_name='Vaqti'),
        ),
        migrations.AlterField(
            model_name='hisobot_ich',
            name='vaqt',
            field=models.DateTimeField(verbose_name='Vaqti'),
        ),
        migrations.AlterField(
            model_name='hisobot_ist',
            name='vaqt',
            field=models.DateTimeField(verbose_name='Vaqti'),
        ),
        migrations.AlterField(
            model_name='hisobot_item',
            name='vaqt',
            field=models.DateTimeField(verbose_name='Vaqti'),
        ),
        migrations.AlterField(
            model_name='hisobot_uzat',
            name='vaqt',
            field=models.DateTimeField(verbose_name='Vaqti'),
        ),
    ]
