# Generated by Django 4.0.1 on 2022-01-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0063_hisobot_full_tur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisobot_full',
            name='tur',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hisobot turi'),
        ),
    ]
