# Generated by Django 4.0.1 on 2022-01-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0064_alter_hisobot_full_tur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisobot_full',
            name='hisobotlar',
            field=models.ManyToManyField(to='foydalanuvchi.hisobot_item', verbose_name='Ishlab chiqarish hisobotlari'),
        ),
    ]
