# Generated by Django 4.0.1 on 2022-01-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0065_alter_hisobot_full_hisobotlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='hisobot_full',
            name='res',
            field=models.CharField(blank=True, max_length=255, verbose_name='Resurslar'),
        ),
    ]
