# Generated by Django 4.0.1 on 2022-01-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0034_alter_resurslar_gj_alter_resurslar_gkal'),
        ('foydalanuvchi', '0066_hisobot_full_res'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='his_ich',
            options={'verbose_name': 'Davriy hisobot', 'verbose_name_plural': '04_0_Resurslar filteri'},
        ),
        migrations.RemoveField(
            model_name='his_ich',
            name='resurs',
        ),
        migrations.AddField(
            model_name='his_ich',
            name='resurs',
            field=models.ManyToManyField(to='s_ad.resurslar', verbose_name='Resurslar'),
        ),
    ]
