# Generated by Django 4.0.1 on 2022-01-31 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0034_alter_resurslar_gj_alter_resurslar_gkal'),
        ('foydalanuvchi', '0067_alter_his_ich_options_remove_his_ich_resurs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='his_ich',
            name='resurs',
        ),
        migrations.AddField(
            model_name='his_ich',
            name='resurs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='s_ad.resurslar', verbose_name='Resurslar'),
            preserve_default=False,
        ),
    ]
