# Generated by Django 4.0.1 on 2022-01-31 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0068_remove_his_ich_resurs_his_ich_resurs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='his_ich',
            name='nomi',
        ),
    ]
