# Generated by Django 4.0.1 on 2022-01-31 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0034_alter_resurslar_gj_alter_resurslar_gkal'),
        ('foydalanuvchi', '0069_remove_his_ich_nomi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ichres',
            name='birlik',
        ),
        migrations.RemoveField(
            model_name='ichres',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='istres',
            name='birlik',
        ),
        migrations.RemoveField(
            model_name='istres',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='sotres',
            name='birlik',
        ),
        migrations.RemoveField(
            model_name='sotres',
            name='nom',
        ),
        migrations.AddField(
            model_name='ichres',
            name='resurs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='s_ad.resurslar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='istres',
            name='resurs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='s_ad.resurslar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sotres',
            name='resurs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='s_ad.resurslar'),
            preserve_default=False,
        ),
    ]
