# Generated by Django 4.0.1 on 2022-01-31 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0070_remove_ichres_birlik_remove_ichres_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hisobot_ich',
            name='birlik',
        ),
        migrations.RemoveField(
            model_name='hisobot_ich',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='hisobot_ist',
            name='birlik',
        ),
        migrations.RemoveField(
            model_name='hisobot_ist',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='hisobot_uzat',
            name='birlik',
        ),
        migrations.RemoveField(
            model_name='hisobot_uzat',
            name='qiymat',
        ),
        migrations.AddField(
            model_name='hisobot_ich',
            name='resurs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foydalanuvchi.ichres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hisobot_ist',
            name='resurs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foydalanuvchi.istres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hisobot_uzat',
            name='resurs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foydalanuvchi.sotres'),
            preserve_default=False,
        ),
    ]
