# Generated by Django 4.0.1 on 2022-02-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0071_remove_hisobot_ich_birlik_remove_hisobot_ich_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hisobot_uzat',
            name='qiymat',
            field=models.FloatField(default=1, verbose_name='Resurs qiymati'),
            preserve_default=False,
        ),
    ]
