# Generated by Django 4.0.1 on 2022-02-01 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0072_hisobot_uzat_qiymat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hisobot_full',
            old_name='res',
            new_name='resurs',
        ),
    ]
