# Generated by Django 4.0.1 on 2022-02-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0034_alter_resurslar_gj_alter_resurslar_gkal'),
        ('foydalanuvchi', '0073_rename_res_hisobot_full_resurs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hisobot_full',
            name='resurs',
        ),
        migrations.AddField(
            model_name='hisobot_full',
            name='resurs',
            field=models.ManyToManyField(to='s_ad.resurslar', verbose_name='Resurslar'),
        ),
    ]
