# Generated by Django 4.0.1 on 2022-02-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0074_remove_hisobot_full_resurs_hisobot_full_resurs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hisobot_full',
            name='hisobotlar',
        ),
        migrations.AddField(
            model_name='hisobot_full',
            name='ich',
            field=models.ManyToManyField(to='foydalanuvchi.hisobot_ich', verbose_name='Ishlab chiqarish hisobotlari'),
        ),
        migrations.AddField(
            model_name='hisobot_full',
            name='ist',
            field=models.ManyToManyField(to='foydalanuvchi.hisobot_ist', verbose_name="Iste'mol hisobotlari"),
        ),
        migrations.AddField(
            model_name='hisobot_full',
            name='sot',
            field=models.ManyToManyField(to='foydalanuvchi.hisobot_uzat', verbose_name='Sotish hisobotlari'),
        ),
    ]
