# Generated by Django 3.2.12 on 2022-02-09 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_ad', '0034_alter_resurslar_gj_alter_resurslar_gkal'),
        ('foydalanuvchi', '0076_alter_hisobot_ich_options_hisobot_full_h_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allfaqir',
            name='admin',
        ),
        migrations.AddField(
            model_name='allfaqir',
            name='boolean_ich',
            field=models.BooleanField(default=1, verbose_name='Ishlab chiqarish/servis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allfaqir',
            name='boolean_sot',
            field=models.BooleanField(default=1, verbose_name='Uzatish/sotish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allfaqir',
            name='dav',
            field=models.OneToOneField(default=11, on_delete=django.db.models.deletion.CASCADE, to='s_ad.davlatlar', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allfaqir',
            name='dbibt',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='s_ad.dbibt', verbose_name='DBIBT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allfaqir',
            name='iftum',
            field=models.OneToOneField(default=11, on_delete=django.db.models.deletion.CASCADE, to='s_ad.iftum', verbose_name='IFTUM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allfaqir',
            name='manzil',
            field=models.TextField(default=1, verbose_name='Manzil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allfaqir',
            name='mobil',
            field=models.CharField(default=11, max_length=9, verbose_name='Korxona raqami'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allfaqir',
            name='tel',
            field=models.CharField(default=1, max_length=9, verbose_name='Korxona raqami'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allfaqir',
            name='thst',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='s_ad.thst', verbose_name='DBIBT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allfaqir',
            name='tum',
            field=models.OneToOneField(default=11, on_delete=django.db.models.deletion.CASCADE, to='s_ad.tumanlar', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allfaqir',
            name='vil',
            field=models.OneToOneField(default=11, on_delete=django.db.models.deletion.CASCADE, to='s_ad.viloyatlar', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allfaqir',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi'),
        ),
    ]
