# Generated by Django 3.2.12 on 2022-02-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0077_auto_20220209_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfaqir',
            name='inn',
            field=models.CharField(blank=True, max_length=50, verbose_name='STIR'),
        ),
        migrations.AlterField(
            model_name='allfaqir',
            name='nomi',
            field=models.CharField(blank=True, max_length=250, verbose_name='Korxona nomi'),
        ),
    ]
