# Generated by Django 3.2.12 on 2022-02-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0078_auto_20220209_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allfaqir',
            old_name='boolean_ich',
            new_name='savol1',
        ),
        migrations.RenameField(
            model_name='allfaqir',
            old_name='boolean_sot',
            new_name='savol2',
        ),
    ]
