# Generated by Django 3.2.12 on 2022-02-10 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0036_alter_viloyatlar_viloyat_kodi'),
        ('foydalanuvchi', '0080_auto_20220210_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfaqir',
            name='dav',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.davlatlar', verbose_name='Davlat'),
        ),
        migrations.AlterField(
            model_name='allfaqir',
            name='dbibt',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.dbibt', verbose_name='DBIBT'),
        ),
        migrations.AlterField(
            model_name='allfaqir',
            name='iftum',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.iftum', verbose_name='IFTUM'),
        ),
        migrations.AlterField(
            model_name='allfaqir',
            name='thst',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.thst', verbose_name='DBIBT'),
        ),
        migrations.AlterField(
            model_name='allfaqir',
            name='tum',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.tumanlar', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='allfaqir',
            name='vil',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.viloyatlar', verbose_name='Viloyat'),
        ),
    ]
