# Generated by Django 3.2.12 on 2022-02-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0082_auto_20220210_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfaqir',
            name='emblem',
            field=models.ImageField(blank=True, upload_to='profile_emb', verbose_name='Emblemasi'),
        ),
    ]
