# Generated by Django 4.0.5 on 2022-09-20 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_ad', '0038_alter_tadbir_options'),
        ('foydalanuvchi', '0083_alter_allfaqir_emblem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfaqir',
            name='emblem',
            field=models.ImageField(blank=True, default='profile_emb/login_emb.jpg', max_length=255, upload_to='profile_emb', verbose_name='Emblemasi'),
        ),
        migrations.AlterField(
            model_name='allfaqir',
            name='mobil',
            field=models.CharField(blank=True, max_length=12, verbose_name='Ish boshqaruvchi raqami'),
        ),
        migrations.AlterField(
            model_name='allfaqir',
            name='tel',
            field=models.CharField(blank=True, max_length=12, verbose_name='Korxona raqami'),
        ),
        migrations.CreateModel(
            name='TexnikTadbir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(verbose_name='Sana')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('tejaldi', models.FloatField(blank=True, verbose_name='Tejalgan energiya miqdori')),
                ('birligi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_ad.birliklar', verbose_name='birlik')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
                ('tadbir', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.tadbir', verbose_name='Tadbir nomi')),
            ],
            options={
                'verbose_name': 'TexnikTadbir',
                'verbose_name_plural': '05_Texnik Tadbirlar',
            },
        ),
        migrations.CreateModel(
            name='ICHMM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(auto_now=True, verbose_name='Sana')),
                ('nomi', models.TextField(blank=True, verbose_name='Mahsulot nomi')),
                ('VVP', models.FloatField(verbose_name='IShlab chiqarilgan mahsulot miqdori')),
                ('pul', models.FloatField(verbose_name='IShlab chiqarilgan mahsulot miqdori')),
                ('birlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_ad.birliklar', verbose_name='birlik')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
                ('pul_birlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_ad.valyuta', verbose_name='Pul birlik')),
            ],
            options={
                'verbose_name': 'ICHMM',
                'verbose_name_plural': '06_ICHMM',
            },
        ),
    ]
