# Generated by Django 4.0.5 on 2022-09-20 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0084_alter_allfaqir_emblem_alter_allfaqir_mobil_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ICHMM',
        ),
    ]
