# Generated by Django 4.0.5 on 2022-09-20 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0038_alter_tadbir_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0085_delete_ichmm'),
    ]

    operations = [
        migrations.CreateModel(
            name='VVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(auto_now=True, verbose_name='Sana')),
                ('nomi', models.TextField(blank=True, verbose_name='Mahsulot nomi')),
                ('VVP', models.FloatField(verbose_name='IShlab chiqarilgan mahsulot miqdori')),
                ('pul', models.FloatField(verbose_name='IShlab chiqarilgan mahsulot miqdori')),
                ('birlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_ad.birliklar', verbose_name='birlik')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
                ('pul_birlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_ad.valyuta', verbose_name='Pul birlik')),
            ],
            options={
                'verbose_name': 'VVP',
                'verbose_name_plural': '06_VVP',
            },
        ),
    ]
