# Generated by Django 4.0.5 on 2022-09-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0086_vvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vvp',
            name='pul',
            field=models.FloatField(verbose_name='Ishlab chiqarilgan mahsulot miqdori pul birligida'),
        ),
        migrations.AlterField(
            model_name='vvp',
            name='sana',
            field=models.DateField(verbose_name='Sana'),
        ),
    ]
