# Generated by Django 4.0.5 on 2022-09-21 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0038_alter_tadbir_options'),
        ('foydalanuvchi', '0087_alter_vvp_pul_alter_vvp_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='texniktadbir',
            name='resurs',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.resurslar', verbose_name='Tadbir nomi'),
        ),
    ]
