# Generated by Django 4.0.5 on 2022-09-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0089_alter_texniktadbir_resurs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texniktadbir',
            name='birligi',
        ),
    ]
