# Generated by Django 4.0.5 on 2022-10-01 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0090_remove_texniktadbir_birligi'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan_ich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Hisobot nomi')),
                ('vaqt', models.DateTimeField(verbose_name='Vaqti')),
                ('qiymat', models.FloatField(verbose_name='Resurs qiymati')),
                ('qiymat_pul', models.FloatField(verbose_name='Resurs qiymati so`mda')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foydalanuvchi.ichres')),
            ],
            options={
                'verbose_name_plural': '02_1_Ishlab chiqarish hisoboti',
                'ordering': ('vaqt',),
            },
        ),
        migrations.CreateModel(
            name='plan_ist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Hisobot nomi')),
                ('vaqt', models.DateTimeField(verbose_name='Vaqti')),
                ('qiymat', models.FloatField(verbose_name='Resurs qiymati')),
                ('qiymat_pul', models.FloatField(verbose_name='Resurs qiymati so`mda')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foydalanuvchi.istres')),
            ],
            options={
                'verbose_name_plural': '02_2_Iste`mol hisoboti',
            },
        ),
        migrations.CreateModel(
            name='plan_uzat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Hisobot nomi')),
                ('vaqt', models.DateTimeField(verbose_name='Vaqti')),
                ('nom', models.TextField(verbose_name='Resurs nomi')),
                ('qiymat', models.FloatField(verbose_name='Resurs qiymati')),
                ('qiymat_pul', models.FloatField(verbose_name='Resurs qiymati so`mda')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foydalanuvchi.sotres')),
            ],
            options={
                'verbose_name_plural': '02_3_Uzatilgan resurs hisoboti',
            },
        ),
        migrations.CreateModel(
            name='plan_umumiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Hisobot nomi')),
                ('vaqt', models.DateTimeField(verbose_name='Vaqti')),
                ('ich', models.ManyToManyField(blank=True, to='foydalanuvchi.plan_ich', verbose_name='Ishlab chiqarish')),
                ('ist', models.ManyToManyField(blank=True, to='foydalanuvchi.plan_ist', verbose_name="Iste'mol")),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uzat', models.ManyToManyField(blank=True, to='foydalanuvchi.plan_uzat', verbose_name='Uzatish/Sotish')),
            ],
            options={
                'verbose_name': 'hisobot_shakli',
                'verbose_name_plural': '02_0_Hisobot shakllari',
            },
        ),
    ]
