# Generated by Django 4.0.5 on 2022-10-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0091_plan_ich_plan_ist_plan_uzat_plan_umumiy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hisobot_ich',
            options={'ordering': ('vaqt',), 'verbose_name_plural': '03_1_Ishlab chiqarish hisoboti'},
        ),
        migrations.AlterModelOptions(
            name='hisobot_ist',
            options={'verbose_name_plural': '03_2_Iste`mol hisoboti'},
        ),
        migrations.AlterModelOptions(
            name='hisobot_item',
            options={'verbose_name': 'hisobot_shakli', 'verbose_name_plural': '03_0_Hisobot shakllari'},
        ),
        migrations.AlterModelOptions(
            name='hisobot_uzat',
            options={'verbose_name_plural': '03_3_Uzatilgan resurs hisoboti'},
        ),
        migrations.AlterModelOptions(
            name='plan_ich',
            options={'ordering': ('vaqt',), 'verbose_name_plural': '02_1_Ishlab chiqarish rejasi'},
        ),
        migrations.AlterModelOptions(
            name='plan_ist',
            options={'verbose_name_plural': '02_2_Iste`mol rejasi'},
        ),
        migrations.AlterModelOptions(
            name='plan_umumiy',
            options={'verbose_name': 'hisobot_shakli', 'verbose_name_plural': '02_0_Umumiy shartnomaviy miqdorlar'},
        ),
        migrations.AlterModelOptions(
            name='plan_uzat',
            options={'verbose_name_plural': '02_3_Uzatilgan resurs rejasi'},
        ),
    ]
