# Generated by Django 4.0.5 on 2022-10-04 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0038_alter_tadbir_options'),
        ('foydalanuvchi', '0092_alter_hisobot_ich_options_alter_hisobot_ist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfaqir',
            name='thst',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.thst', verbose_name='THST'),
        ),
    ]
