# Generated by Django 4.0.5 on 2022-10-14 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_ad', '0038_alter_tadbir_options'),
        ('foydalanuvchi', '0093_alter_allfaqir_thst'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTT_reja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_ID', models.FloatField(blank=True, verbose_name='Tejalgan energiya miqdori')),
                ('sana', models.DateField(auto_now=True, verbose_name='Sana')),
                ('nomi', models.TextField(blank=True, verbose_name='Nomi')),
                ('dan', models.DateField(verbose_name='dan')),
                ('gacha', models.DateField(verbose_name='gacha')),
                ('jumladan', models.BooleanField(verbose_name='Jumladan miqdoriy ulushi mavjud')),
                ('tejaladi', models.FloatField(blank=True, verbose_name='Tejaladigan energiya miqdori')),
                ('tejaladi_pul', models.FloatField(blank=True, verbose_name='Tejaladigan energiya miqdori')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('guruh', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.tadbir', verbose_name='Tadbir nomi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'TTT_reja',
                'verbose_name_plural': '06_TTT_rejalar',
            },
        ),
        migrations.CreateModel(
            name='TTT_umumiy_reja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_ID', models.FloatField(blank=True, verbose_name='Tejalgan energiya miqdori')),
                ('sana', models.DateField(auto_now=True, verbose_name='Sana')),
                ('tejaladi', models.FloatField(blank=True, verbose_name='Tejaladigan energiya miqdori')),
                ('tejaladi_pul', models.FloatField(blank=True, verbose_name='Tejaladigan energiya miqdori')),
                ('dan', models.DateField(verbose_name='dan')),
                ('gacha', models.DateField(verbose_name='gacha')),
                ('TTT_rejalar', models.ManyToManyField(blank=True, to='foydalanuvchi.ttt_reja', verbose_name='TTT lar')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
                ('resurs', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.resurslar', verbose_name='Tejalgan resurs')),
            ],
            options={
                'verbose_name': 'TTT_umumiy_reja',
                'verbose_name_plural': '06_TTT_umumiy_rejalar',
            },
        ),
    ]
