# Generated by Django 4.0.5 on 2022-10-17 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0038_alter_tadbir_options'),
        ('foydalanuvchi', '0094_ttt_reja_ttt_umumiy_reja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ttt_reja',
            options={'verbose_name': 'TTT_reja', 'verbose_name_plural': '05_TTT_rejalar'},
        ),
        migrations.AlterModelOptions(
            name='ttt_umumiy_reja',
            options={'verbose_name': 'TTT_umumiy_reja', 'verbose_name_plural': '05_TTT_umumiy_rejalar'},
        ),
        migrations.RemoveField(
            model_name='ttt_reja',
            name='jumladan',
        ),
        migrations.AlterField(
            model_name='ttt_reja',
            name='T_ID',
            field=models.TextField(blank=True, verbose_name='T_ID'),
        ),
        migrations.AlterField(
            model_name='ttt_reja',
            name='dan',
            field=models.DateField(blank=True, null=True, verbose_name='dan'),
        ),
        migrations.AlterField(
            model_name='ttt_reja',
            name='gacha',
            field=models.DateField(blank=True, null=True, verbose_name='gacha'),
        ),
        migrations.AlterField(
            model_name='ttt_reja',
            name='guruh',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.tadbir', verbose_name='Tadbir guruhi'),
        ),
        migrations.AlterField(
            model_name='ttt_reja',
            name='tejaladi',
            field=models.FloatField(blank=True, default=0, verbose_name='Tejaladigan energiya miqdori'),
        ),
        migrations.AlterField(
            model_name='ttt_reja',
            name='tejaladi_pul',
            field=models.FloatField(blank=True, default='0', verbose_name='Tejaladigan energiya miqdori'),
        ),
        migrations.AlterField(
            model_name='ttt_umumiy_reja',
            name='dan',
            field=models.DateField(blank=True, verbose_name='dan'),
        ),
        migrations.AlterField(
            model_name='ttt_umumiy_reja',
            name='gacha',
            field=models.DateField(blank=True, verbose_name='gacha'),
        ),
    ]
