# Generated by Django 4.0.5 on 2022-10-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0095_alter_ttt_reja_options_alter_ttt_umumiy_reja_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttt_umumiy_reja',
            name='aktiv',
            field=models.BooleanField(default=1, verbose_name='Aktivlik'),
            preserve_default=False,
        ),
    ]
