# Generated by Django 4.0.5 on 2022-10-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0096_ttt_umumiy_reja_aktiv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttt_umumiy_reja',
            name='aktiv',
        ),
        migrations.AddField(
            model_name='ttt_reja',
            name='aktiv',
            field=models.BooleanField(default=1, verbose_name='Aktivlik'),
            preserve_default=False,
        ),
    ]
