# Generated by Django 4.0.5 on 2022-10-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0097_remove_ttt_umumiy_reja_aktiv_ttt_reja_aktiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttt_reja',
            name='bajarilishi',
            field=models.FloatField(blank=True, default=0, verbose_name='Bajarilishi'),
        ),
        migrations.AddField(
            model_name='ttt_reja',
            name='nega',
            field=models.TextField(blank=True, verbose_name='Nega bajarilmadi'),
        ),
        migrations.AddField(
            model_name='ttt_reja',
            name='tejaldi',
            field=models.FloatField(blank=True, default=0, verbose_name='Tejaldigan energiya miqdori'),
        ),
        migrations.AddField(
            model_name='ttt_reja',
            name='tejaldi_pul',
            field=models.FloatField(blank=True, default='0', verbose_name='Tejladigan energiya miqdori'),
        ),
        migrations.AddField(
            model_name='ttt_reja',
            name='tugadi',
            field=models.DateField(blank=True, null=True, verbose_name='gacha'),
        ),
        migrations.AddField(
            model_name='ttt_umumiy_reja',
            name='bajarilishi',
            field=models.FloatField(blank=True, default=0, verbose_name='Bajarilishi'),
        ),
        migrations.AddField(
            model_name='ttt_umumiy_reja',
            name='tejaldi',
            field=models.FloatField(blank=True, default=0, verbose_name='Tejaldigan energiya miqdori'),
        ),
        migrations.AddField(
            model_name='ttt_umumiy_reja',
            name='tejaldi_pul',
            field=models.FloatField(blank=True, default='0', verbose_name='Tejladigan energiya miqdori'),
        ),
        migrations.AddField(
            model_name='ttt_umumiy_reja',
            name='tugash_sanasi',
            field=models.DateField(blank=True, null=True, verbose_name='gacha'),
        ),
        migrations.AddField(
            model_name='ttt_umumiy_reja',
            name='tugatildi',
            field=models.BooleanField(default=False, verbose_name='Tugatildi'),
        ),
        migrations.AlterField(
            model_name='ttt_reja',
            name='aktiv',
            field=models.BooleanField(default=False, verbose_name='Aktivlik'),
        ),
    ]
