# Generated by Django 4.0.5 on 2022-10-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0098_ttt_reja_bajarilishi_ttt_reja_nega_ttt_reja_tejaldi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttt_reja',
            name='tugadi',
        ),
        migrations.AddField(
            model_name='ttt_reja',
            name='tugadi_sanasi',
            field=models.DateField(blank=True, null=True, verbose_name='Tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='ttt_umumiy_reja',
            name='tugash_sanasi',
            field=models.DateField(blank=True, null=True, verbose_name='Tugash sanasi'),
        ),
    ]
