# Generated by Django 4.0.5 on 2022-10-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0099_remove_ttt_reja_tugadi_ttt_reja_tugadi_sanasi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttt_reja',
            name='T_ID',
            field=models.IntegerField(blank=True, verbose_name='T_ID'),
        ),
        migrations.AlterField(
            model_name='ttt_reja',
            name='tejaldi',
            field=models.FloatField(blank=True, default=0, verbose_name='Tejalgan energiya miqdori'),
        ),
        migrations.AlterField(
            model_name='ttt_reja',
            name='tejaldi_pul',
            field=models.FloatField(blank=True, default='0', verbose_name='Tejalgan energiya miqdori'),
        ),
        migrations.AlterField(
            model_name='ttt_umumiy_reja',
            name='T_ID',
            field=models.IntegerField(blank=True, verbose_name='Tejalgan energiya miqdori'),
        ),
        migrations.AlterField(
            model_name='ttt_umumiy_reja',
            name='tejaldi',
            field=models.FloatField(blank=True, default=0, verbose_name='Tejalgan energiya miqdori'),
        ),
        migrations.AlterField(
            model_name='ttt_umumiy_reja',
            name='tejaldi_pul',
            field=models.FloatField(blank=True, default='0', verbose_name='Tejlgan energiya miqdori'),
        ),
    ]
