# Generated by Django 4.0.5 on 2022-10-22 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0046_alter_resurslar_birlik'),
        ('foydalanuvchi', '0100_alter_ttt_reja_t_id_alter_ttt_reja_tejaldi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hisobot_full',
            name='koef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.yaxlitlash', verbose_name='Koeffitsient'),
        ),
    ]
