# Generated by Django 4.0.5 on 2022-10-24 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0101_hisobot_full_koef'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='his_ich',
            options={'verbose_name': 'hisobot', 'verbose_name_plural': '04_2_Hisobot_bolasi'},
        ),
    ]
