# Generated by Django 4.0.5 on 2022-10-25 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0102_alter_his_ich_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfaqir',
            name='TexnikTadbir',
            field=models.ManyToManyField(blank=True, to='foydalanuvchi.ttt_umumiy_reja', verbose_name='Texnik tadbirlar'),
        ),
        migrations.AddField(
            model_name='allfaqir',
            name='VVP',
            field=models.ManyToManyField(blank=True, to='foydalanuvchi.vvp', verbose_name='Ishlab chiqarilgan mahsulotlar'),
        ),
        migrations.AddField(
            model_name='allfaqir',
            name='fakt',
            field=models.ManyToManyField(blank=True, to='foydalanuvchi.hisobot_item', verbose_name='Fakt hisobotlari'),
        ),
        migrations.AddField(
            model_name='allfaqir',
            name='hisobot',
            field=models.ManyToManyField(blank=True, to='foydalanuvchi.hisobot_full', verbose_name='Ishlab chiqarilgan mahsulotlar'),
        ),
        migrations.AddField(
            model_name='allfaqir',
            name='reja',
            field=models.ManyToManyField(blank=True, to='foydalanuvchi.plan_umumiy', verbose_name='Reja hisobotlari'),
        ),
        migrations.RemoveField(
            model_name='allfaqir',
            name='owner',
        ),
        migrations.AddField(
            model_name='allfaqir',
            name='owner',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Xodimlar'),
        ),
    ]
