# Generated by Django 4.0.5 on 2022-10-26 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kirish', '0009_auto_20220209_0352'),
        ('foydalanuvchi', '0103_allfaqir_texniktadbir_allfaqir_vvp_allfaqir_fakt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfaqir',
            name='funksiya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kirish.savolnoma', verbose_name='Funksiyalari'),
        ),
    ]
