# Generated by Django 4.0.5 on 2022-11-13 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0104_allfaqir_funksiya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allfaqir',
            name='owner',
        ),
        migrations.AddField(
            model_name='allfaqir',
            name='owner',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Xodimlar'),
            preserve_default=False,
        ),
    ]
