# Generated by Django 4.0.5 on 2022-11-13 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0105_remove_allfaqir_owner_allfaqir_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfaqir',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Xodimlar'),
        ),
    ]
