# Generated by Django 4.0.5 on 2022-11-13 11:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0107_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='test2',
        ),
    ]
