# Generated by Django 4.0.5 on 2022-11-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0108_rename_test_test2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test2',
        ),
    ]
