# Generated by Django 4.0.5 on 2022-11-16 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0047_res_maqsad'),
        ('foydalanuvchi', '0117_alter_allfaqir_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ichres',
            name='maqsad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.res_maqsad', verbose_name="Ishlatish yo'nalishi"),
        ),
        migrations.AddField(
            model_name='istres',
            name='maqsad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.res_maqsad', verbose_name="Ishlatish yo'nalishi"),
        ),
        migrations.AddField(
            model_name='sotres',
            name='maqsad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.res_maqsad', verbose_name="Ishlatish yo'nalishi"),
        ),
    ]
