# Generated by Django 4.0.5 on 2022-11-17 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0049_alter_res_maqsad_options_alter_res_maqsad_checker_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0118_ichres_maqsad_istres_maqsad_sotres_maqsad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ichres',
            name='hajm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='s_ad.yaxlitlash', verbose_name='hajm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='istres',
            name='hajm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.yaxlitlash', verbose_name='hajm'),
        ),
        migrations.AlterField(
            model_name='sotres',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
