# Generated by Django 4.0.5 on 2022-11-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0119_ichres_hajm_istres_hajm_alter_sotres_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ichres',
            name='hajm',
        ),
    ]
