# Generated by Django 4.0.5 on 2022-11-17 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0049_alter_res_maqsad_options_alter_res_maqsad_checker_and_more'),
        ('foydalanuvchi', '0120_remove_ichres_hajm'),
    ]

    operations = [
        migrations.AddField(
            model_name='ichres',
            name='hajm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.yaxlitlash', verbose_name='hajm'),
        ),
    ]
