# Generated by Django 4.0.5 on 2022-11-17 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0050_remove_resurslar_yaxlit'),
        ('foydalanuvchi', '0121_ichres_hajm'),
    ]

    operations = [
        migrations.AddField(
            model_name='sotres',
            name='hajm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.yaxlitlash', verbose_name='hajm'),
        ),
    ]
