# Generated by Django 4.0.5 on 2022-11-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0122_sotres_hajm'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfaqir',
            name='ichres',
            field=models.ManyToManyField(blank=True, to='foydalanuvchi.ichres', verbose_name="Ish chiq/xizmat ko'rsatish resurslari"),
        ),
        migrations.AddField(
            model_name='allfaqir',
            name='istres',
            field=models.ManyToManyField(blank=True, to='foydalanuvchi.istres', verbose_name="Iste'mol resurslari"),
        ),
        migrations.AddField(
            model_name='allfaqir',
            name='sotres',
            field=models.ManyToManyField(blank=True, to='foydalanuvchi.sotres', verbose_name='Uzat/sot resurslari'),
        ),
    ]
