# Generated by Django 4.0.5 on 2022-11-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0055_alter_elon_url'),
        ('foydalanuvchi', '0123_allfaqir_ichres_allfaqir_istres_allfaqir_sotres'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfaqir',
            name='elon',
            field=models.ManyToManyField(blank=True, to='s_ad.elon', verbose_name='Xabarlar'),
        ),
    ]
