# Generated by Django 4.0.5 on 2022-11-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0124_allfaqir_elon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ichres',
            name='aktiv',
            field=models.BooleanField(default=1, verbose_name='Aktivlik'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='istres',
            name='aktiv',
            field=models.BooleanField(default=1, verbose_name='Aktivlik'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sotres',
            name='aktiv',
            field=models.BooleanField(default=1, verbose_name='Aktivlik'),
            preserve_default=False,
        ),
    ]
