# Generated by Django 4.0.5 on 2022-11-22 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0125_ichres_aktiv_istres_aktiv_sotres_aktiv'),
    ]

    operations = [
        migrations.CreateModel(
            name='oraliq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dan', models.DateField(auto_now=True, verbose_name='dan')),
                ('gacha', models.DateField(auto_now=True, verbose_name='dan')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'oraliq',
                'verbose_name_plural': 'oraliqlar',
            },
        ),
    ]
