# Generated by Django 4.0.5 on 2022-12-19 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0126_oraliq'),
    ]

    operations = [
        migrations.CreateModel(
            name='qtemholat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(verbose_name='Sana')),
                ('panel', models.FloatField(verbose_name="O'rnatilgan panel")),
                ('kollektor', models.FloatField(verbose_name="O'rnatilgan kollektor")),
                ('yypanel', models.FloatField(verbose_name="Yil yakunigacha o'rnatiladigan panel")),
                ('yykollektor', models.FloatField(verbose_name="Yil yakunigacha o'rnatiladigan kollektor")),
                ('panel23', models.FloatField(verbose_name="2023 yilda o'rnatiladigan panel")),
                ('kollektor23', models.FloatField(verbose_name="2023 yilda o'rnatiladigan kollektor")),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'qtemholat',
                'verbose_name_plural': 'qtemholatlar',
            },
        ),
    ]
