# Generated by Django 4.0.5 on 2022-12-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0128_qtemholat_aktiv_alter_qtemholat_kollektor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qtemholat',
            name='kollektor',
            field=models.FloatField(blank=True, null=True, verbose_name="O'rnatilgan kollektor"),
        ),
        migrations.AlterField(
            model_name='qtemholat',
            name='kollektor23',
            field=models.FloatField(blank=True, null=True, verbose_name="2023 yilda o'rnatiladigan kollektor"),
        ),
        migrations.AlterField(
            model_name='qtemholat',
            name='panel',
            field=models.FloatField(blank=True, null=True, verbose_name="O'rnatilgan panel"),
        ),
        migrations.AlterField(
            model_name='qtemholat',
            name='panel23',
            field=models.FloatField(blank=True, null=True, verbose_name="2023 yilda o'rnatiladigan panel"),
        ),
        migrations.AlterField(
            model_name='qtemholat',
            name='yykollektor',
            field=models.FloatField(blank=True, null=True, verbose_name="Yil yakunigacha o'rnatiladigan kollektor"),
        ),
        migrations.AlterField(
            model_name='qtemholat',
            name='yypanel',
            field=models.FloatField(blank=True, null=True, verbose_name="Yil yakunigacha o'rnatiladigan panel"),
        ),
    ]
