# Generated by Django 4.0.5 on 2023-02-17 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_ad', '0066_remove_elon_masala_elon_birlik_elon_hajm_elon_maqsad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0129_alter_qtemholat_kollektor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='taklif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ish', models.TextField(blank=True, verbose_name='Bajariladigan ish')),
                ('tejalgan', models.FloatField(blank=True, verbose_name='Tejaladigan energiya miqdori')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('guruh', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.tadbir', verbose_name='Tadbir guruhi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
                ('resurs', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_ad.resurslar', verbose_name='Tejalgan resurs')),
            ],
            options={
                'verbose_name': 'taklif',
                'verbose_name_plural': 'takliflar',
            },
        ),
    ]
