# Generated by Django 4.0.5 on 2023-02-21 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0130_taklif'),
    ]

    operations = [
        migrations.CreateModel(
            name='sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.TextField(blank=True, verbose_name='Mahsulot nomi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
                ('zavod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foydalanuvchi.allfaqir', verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'sex',
                'verbose_name_plural': 'sexlar',
            },
        ),
    ]
