# Generated by Django 4.0.5 on 2023-02-25 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foydalanuvchi', '0131_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='hisobot_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistik', models.BooleanField(default=False, verbose_name='statistik')),
                ('samaradorlik', models.BooleanField(default=False, verbose_name='samaradorlik')),
                ('sex', models.BooleanField(default=False, verbose_name='sex')),
                ('zavod', models.BooleanField(default=False, verbose_name='zavod')),
                ('oy', models.BooleanField(default=False, verbose_name='oy')),
                ('chorak', models.BooleanField(default=False, verbose_name='chorak')),
                ('yil', models.BooleanField(default=False, verbose_name='yil')),
                ('korxona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foydalanuvchi.allfaqir', verbose_name='Egasi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'hisobot_turi',
                'verbose_name_plural': 'hisobot_turlari',
            },
        ),
        migrations.CreateModel(
            name='bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.TextField(blank=True, verbose_name='Mahsulot nomi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
                ('zavod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foydalanuvchi.allfaqir', verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'sex',
                'verbose_name_plural': 'sexlar',
            },
        ),
    ]
