# Generated by Django 4.0.5 on 2023-02-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0132_hisobot_turi_bolim'),
    ]

    operations = [
        migrations.AddField(
            model_name='hisobot_full',
            name='qanday',
            field=models.TextField(blank=True, verbose_name='Qanday turdagi'),
        ),
    ]
