# Generated by Django 4.0.5 on 2023-02-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foydalanuvchi', '0134_hisobot_samaradorlik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hisobot_samaradorlik',
            name='ich',
        ),
        migrations.RemoveField(
            model_name='hisobot_samaradorlik',
            name='ist',
        ),
        migrations.RemoveField(
            model_name='hisobot_samaradorlik',
            name='sot',
        ),
        migrations.AddField(
            model_name='hisobot_samaradorlik',
            name='h_itemp',
            field=models.ManyToManyField(to='foydalanuvchi.plan_umumiy', verbose_name='Plan hisobot'),
        ),
    ]
