# Generated by Django 4.0.1 on 2022-01-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_book_chapter_section_subject_chapter_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Kitob', 'verbose_name_plural': '00_1_Kitoblar'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Bob', 'verbose_name_plural': '00_3_Boblar'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': "Bo'lim", 'verbose_name_plural': "00_2_Bo'limlar"},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Mavzu', 'verbose_name_plural': '00_4_Mavzular'},
        ),
        migrations.AlterField(
            model_name='book',
            name='sana',
            field=models.DateField(verbose_name='Published date'),
        ),
    ]
