# Generated by Django 4.0.1 on 2022-02-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_book_options_alter_chapter_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='book',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='book',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='book',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='section',
        ),
        migrations.AddField(
            model_name='book',
            name='section',
            field=models.ManyToManyField(to='pages.Section', verbose_name="Bo'lim"),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ManyToManyField(to='pages.Subject', verbose_name='Mavzu'),
        ),
        migrations.AddField(
            model_name='section',
            name='chapter',
            field=models.ManyToManyField(to='pages.Chapter', verbose_name='Boblar'),
        ),
        migrations.AddField(
            model_name='subject',
            name='vaqt',
            field=models.DateField(auto_now=True),
        ),
    ]
