# Generated by Django 4.0.1 on 2022-02-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_chapter_book_remove_chapter_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='emblem',
            field=models.ImageField(blank=True, default='profile_emb/book_default.jpg', max_length=255, upload_to='profile_emb', verbose_name='Emblemasi'),
        ),
    ]
