# Generated by Django 4.0.1 on 2022-02-23 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0005_book_emblem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Javob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('javob', models.TextField(verbose_name='Javob')),
                ('tip', models.BooleanField(verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': '01_1_Javoblar',
            },
        ),
        migrations.CreateModel(
            name='Savol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.TextField(verbose_name='Savol')),
                ('javob', models.ManyToManyField(to='pages.Javob', verbose_name='Javob')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': '01_2_Savollar',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='emblem',
            field=models.ImageField(blank=True, default='profile_emb/book_default.png', max_length=255, upload_to='profile_emb', verbose_name='Emblemasi'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=120)),
                ('sana', models.DateField(verbose_name="Qo'shilgan vaqti")),
                ('davomiylik', models.TimeField(verbose_name='Ishlash vaqti')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('savol', models.ManyToManyField(to='pages.Savol', verbose_name='Test savoli')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': '01_3_Testlar',
            },
        ),
    ]
