# Generated by Django 4.0.1 on 2022-02-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_javob_savol_alter_book_emblem_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='javob',
            name='tip',
        ),
        migrations.RemoveField(
            model_name='savol',
            name='javob',
        ),
        migrations.AddField(
            model_name='savol',
            name='j1',
            field=models.ManyToManyField(to='pages.Javob', verbose_name="To'g'ri javob"),
        ),
    ]
