# Generated by Django 4.0.1 on 2022-02-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_javob_tip_remove_savol_javob_savol_j1'),
    ]

    operations = [
        migrations.AddField(
            model_name='savol',
            name='j2',
            field=models.ManyToManyField(blank=True, related_name='j2', to='pages.Javob', verbose_name="Noto'g'ri javob"),
        ),
        migrations.AlterField(
            model_name='savol',
            name='j1',
            field=models.ManyToManyField(blank=True, related_name='j1', to='pages.Javob', verbose_name="To'g'ri javob"),
        ),
    ]
