# Generated by Django 3.2.12 on 2022-04-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_savol_j2_alter_savol_j1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Mavzu', 'verbose_name_plural': '00_3_Mavzular'},
        ),
        migrations.RemoveField(
            model_name='section',
            name='chapter',
        ),
        migrations.AddField(
            model_name='section',
            name='mavzu',
            field=models.ManyToManyField(to='pages.Subject', verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='book',
            name='section',
            field=models.ManyToManyField(blank=True, to='pages.Section', verbose_name="Bo'lim"),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
