# Generated by Django 3.2.12 on 2022-04-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20220415_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='fayl',
            field=models.FileField(blank=True, upload_to=None, verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='section',
            name='icon',
            field=models.TextField(blank=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='section',
            name='mavzu',
            field=models.ManyToManyField(blank=True, to='pages.Subject', verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='section',
            name='nomi',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
