# Generated by Django 3.2.12 on 2022-04-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20220416_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='holat',
            field=models.BooleanField(default=1, verbose_name='Aktiv'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='fayl',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/None/1-maruza', upload_to=None, verbose_name='Fayl'),
        ),
    ]
